### ISSUE TITLE
Add language detection in /index.html

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#1]
As we only serve static sites, the language detection should be done by JavaScript (or is there any other option using Jekyll on Netlify?)

**Comment by kskarthik** [comment]
You mean automatic language detection by using users location?

**Comment by r10s** [comment]
I thought of simply language detection by reading the users preferences, sth. like this: http://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference#answer-26889118

- plus a simple JavaScript redirect to /en/ , /de/ and the polish site. 
- it should also be easy to extent to additional languages 
- it should not include any externall libs (jQuery or sth. like that)
- if JavaScript is disabled, the fallback sould be the existing english page, I think we have to wrap the `<meta refresh>` by `<noscript>` for this purpose

**Comment by r10s** [comment]
Seems as if there is a smarter Netlify-solution that does not require JavaScript: https://www.netlify.com/docs/redirects/#geoip-and-language-based-redirects

**Comment by r10s** [comment]
It's not 100% clear to me if this will work in the pro/opensource plan; I've just asked them and we will see.

**Comment by r10s** [comment]
Language based redirects are not available in Netlify's Pro-plan. Using JavaScript therefore.
