### ISSUE TITLE
Advertise Delta/Desktop and Delta/iOS (testflight) on download page

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#104]
there also was a blog post recently about this: 
https://delta.chat/en/2018-10-03-desktop-update

**Comment by r10s** [comment]
yeah, and also ios can be shown more prominently there.

**Comment by r10s** [comment]
wrt ios: maybe we should add the link https://testflight.apple.com/join/WVoYFOZe directly? e-mails are no longer required, cc @jonasreinsch

**Comment by jonasreinsch** [comment]
fine with me to include the link. Replaced the mailto-address already with the link in the README.
