### ISSUE TITLE
Add link to blog to the main menu

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-pages#121]
Currently there's no way to easy view all blog posts. Adding a link to `delta.chat/<lang>/blog` should solve this.

EDIT: Oh the menu entry is called news. But looked out for blog. Not sure what's more convenient.

**Comment by r10s** [comment]
maybe we should just rename it back to "Blog" - it's also referred from the homepage as a "Blog". this may result in a bit less confusion.

apart from that, i think esp. when looking at some older posts, the wording "Blog" is clearer as it points out more that posts may just reflect the opinion of the respective authors at a given time and are not necessarily "projects news". 

cc @hpk42

**Comment by hpk42** [comment]
On Sun, Jan 27, 2019 at 08:45 -0800, björn petersen wrote:
> maybe we should just rename it back to "Blog" - it's also referred from the homepage as a "Blog". this may result in a bit less confusion.

k, feel free to change it back. 
 
> apart from that, i think esp. when looking at some older posts, the wording "Blog" is clearer as it points out more that posts may just reflect the opinion of the respective authors at a given time and are not necessarily "projects news". 

i guess most people will nevertheless take the Blog as "project news" 
because it's clear that "the project" somehow chooses who posts there and what ;)
