### ISSUE TITLE
Broken link in `en` FAQ

### ISSUE THREAD

**Issue by tnorris** [deltachat/deltachat-pages#122]
Hi Folks,

I was interested in the technical details of Delta Chat, but the link in the FAQ (https://delta.chat/en/help#im-interested-in-the-technical-details-can-you-tell-me-more) is broken.

I would have submitted a PR, but after poking around in a few repos (https://github.com/deltachat/deltachat-core/tree/master/docs, https://github.com/deltachat/deltachat-android/tree/master/docs) I only seemed to find release-eng stuff.

Cheers.

**Comment by r10s** [comment]
@tnorris thanks for the hint, the file was lost on the move from https://github.com/deltachat/deltachat-android-ii/ to https://github.com/deltachat/deltachat-android/, i've just re-added it in https://github.com/deltachat/deltachat-android/commit/b40b6a751a301fda0daba81aeee4a347c6f540bb
