### ISSUE TITLE
Subsitute "alignment" in GDPR page with something more intuitive

### ISSUE THREAD

**Issue by ujdhesa** [deltachat/deltachat-pages#126]
Hello,

The string in question is the following:

- **Data minimization**: No alignment or uploading of the address-book content.

If my understanding of the explanation offered to me is correct, the _alignment_ here means the ability of a service to peak at your address book (without your knowledge?) and copy from your data.

The word chosen doesn't convey this meaning, at least not at the first contact. If changing it is not an option, at least a translator's comment in the string might help.

Regards,
Besnik

**Comment by r10s** [comment]
cc @hpk42 @jankass

**Comment by testbird** [comment]
I guess what is meant is uploading hashes of contact details (i.e. phonenumbers re-identifiable in the list of all existing phone numbers, in the address-book of anybody else, or in the white pages).

A wording that may be better understandable and translatable may be "taking electronic fingerprints of contacts in the address-book and calling-lists"

**Comment by hpk42** [comment]
we stroke "alignment", see online page in the privacy statement.  -- it's not very useful and "no uploading" of addressbook is already as clear as it gets.
