### ISSUE TITLE
link directly to the Google Play page

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#134]
@adbenitez pointed that out via irc.
@r10s it's still beta isn't it? should we wait with adding the link then?

**Comment by r10s** [comment]
no, i think we can add a link to the beta version as we did for ios.

however, we should still clearly claim that we're still in beta-mode.

**Comment by r10s** [comment]
added a pr, preview: https://deploy-preview-135--deltachat.netlify.com/en/download

**Comment by webratte** [comment]
Wouldn't it be better redirect to the Play store download?
Take a look to this:
https://play.google.com/store/apps/details?id=chat.delta&hl

**Comment by r10s** [comment]
> Wouldn't it be better redirect to the Play store download?

i did not expect that this page worked :)

has someone tested this - does the install from the playstore works just by using this link?

what also would be interesting: if i search for "Delta Chat" in the play store - can i install it directly from there without going over  the delta.chat homepage?

(it's a bit hard to test this with my testing devices which are not really untouched wrt to delta.chat, cookies, now google and whatever. so if it works for me, this does not say anything :)

**Comment by webratte** [comment]
Yes, it works.
I and my wife have installed this way.

You also can share it via share button in play store app for Android
This way you got this link:
https://play.google.com/store/apps/details?id=chat.delta

**Comment by webratte** [comment]
A friend of me just tested it.
He never before touched Delta Chat (no preview or something else)
And for him it also works fine.

**Comment by Simon-Laux** [comment]
It works fune for me too, I can even find it in the search in gplay. 

Am 17. Februar 2019 10:52:49 MEZ schrieb webratte <notifications@github.com>:
>A friend of me just tested it.
>He never before touched Delta Chat (no preview or something else)
>And for him it also works fine.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-pages/issues/134#issuecomment-464435973

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by r10s** [comment]
i see, https://play.google.com/store/apps/details?id=chat.delta seems to work always, indeed.

seems as if https://play.google.com/apps/testing/chat.delta is only needed for _closed_ betas.

doing a pr.
