### ISSUE TITLE
Need for a prominent help or wiki page for provider settings

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-pages#149]
Experience with new users first installation of DC with various providers shows most of time problems with provider settings.

1. currently it's hard to find a detailed description how to set up known problematic provider's settings.
2. current descriptons at support forum partly seems to be wrong or outdated.

For new users it's hard to find provider settings at current web site. So without assistance of experienced used of DC it's impossible for a standard user to commission DC to a working state. Most of new users will throw away DC if they will run into this issue.

A prominent provider wiki or help is needed.

**Comment by csb0730** [comment]
Current solution by support forum is not a good solution!

**Comment by hpk42** [comment]
I mostly agree -- i think it could be its own little project to organize feedback and show useful hints about providers.  Neither the support forum nor github appear to be good places for this.  Then again, maybe having a github repo with one-page-per-provider and a web form/page that allows submitting "solutions" or "bugs" for getting setup with a particular provider, could do the trick.  I guess a submission should typically translate into a PR.  Not sure it makes sense to directly think about localization. Starting with text files that are rendered onto the delta.chat page, and only allowing PRs would be a start, the submission form could come later.  We could also tell people to submit info to the support forum and then see to have people who transfer it to the provider overview.  This "curation" step has the advantage that the information is probably presented more consistently.

**Comment by csb0730** [comment]
@hpk42 - Yes, It should be an own little project, so that everyone is aware of some issues with special providers. And that people see the requirement and have an easy single point of information where to address feedback from issues seen.

IMHO, a second possibility could be to add some provider related files to DC sources which are to be shown as prominent help in case of configuration errors while first DC setup:

For example:
- provider.t-online.de.txt
- provider.outlook.de.txt
- provider.outlook.com.txt
- provider.yahoo.net.txt

File should describe every step necessary to get provider working in detail and/or known issues which cannot be solved! (no autocrypt header transport for example).

**Comment by hpk42** [comment]
ok, all fine. At this point it's about someone starting this little project, not acquiring more requirements/wishes i guess ;)

**Comment by Simon-Laux** [comment]
I started a dedicated provider overview page https://github.com/deltachat/provider-overview.
Though it's not done and has no preview yet.

It currently looks like this:
![provider](https://user-images.githubusercontent.com/18725968/58340515-5a5a6a80-7e4c-11e9-9482-3d32658a1526.png)

**Comment by endbacher** [comment]
@csb0730 @Simon-Laux  I agree with the initial post, for the time being I'd like to propose to 
- link https://providers.delta.chat/ at least to https://delta.chat/de/download (if you download you will need to do the setup afterwards, perhaps under "Links" if not into it's own section to be created) and https://delta.chat/de/ (initial page) to find required settings / glitches directly. 
- update Provider Overview link on https://delta.chat/de/help#funktioniert-delta-chat-mit-meinem-e-mail-anbieter to https://providers.delta.chat/ as well instead/in addition to the forum link.

Not sure how / who can update the main web page (update: created an update and launched pull request but no idea if this is the correct/desired procedure), at least I didn't want to add anything to the German translation (finished now by the way but someone with some more detailed insight into the legal stuff should look into https://delta.chat/de/gdpr once update with translation becomes available to avoid any issues related to wording).  

IMHO if we don't want to have the app only used by techies the setup and information should be as clear as possible for the average user.

**Comment by ghost** [comment]
- [x] The provider page is now linked at both get.delta.chat and the FAQ.
- [x] There is a separate project for this.
- [ ] The information on how to configure problematic providers is currently integrated into the app: https://github.com/orgs/deltachat/projects/21

Thanks everyone :)
