### ISSUE TITLE
FAQ: What happens to email in my normal inbox if I sign up for delta chat?

### ISSUE THREAD

**Issue by trosel** [deltachat/deltachat-pages#171]
https://github.com/deltachat/deltachat-pages/blob/master/en/help.md

Curious about what happens to my gmail inbox if I use it with Delta Chat, for example. Will I see a bunch of garbled code emails coming into the webapp gmail inbox?

**Comment by trosel** [comment]
Additionally, what happens to my friend's email inbox if they don't have delta chat and I message them?

Will they see some nonsense messages coming in from my delta chat activity?

**Comment by trosel** [comment]
A connected question:

> Can I keep my normal email inbox if I use the email with delta chat? Or is there no going back?

**Comment by r10s** [comment]
> Curious about what happens to my gmail inbox if I use it with Delta Chat, for example. Will I see a bunch of garbled code emails coming into the webapp gmail inbox?

you will see an folder with the name "DeltaChat" that will contain the chat messages then

> Can I keep my normal email inbox if I use the email with delta chat? Or is there no going back?

you can. delta chat tries to separate chats from normal emails, the letter stay in the inbox, chat-messages are moved to the DeltaChat folder. if you want to stop using DeltaChat, just delete this folder - or move or keek it as you like.

in general, for user support, please use the support forum at https://support.delta.chat - this issue tracker is more about bugs and to coordinate changes.

**Comment by trosel** [comment]
If you answer the question here, I can add these to the page in a PR. That was my intention.

**Comment by r10s** [comment]
okay, great. but i think answers can also go from the forum to the faq. i just think the chance is larger that things are answered in the support forum :)
