### ISSUE TITLE
FAQ: Will Delta Chat drain my phone battery?

### ISSUE THREAD

**Issue by trosel** [deltachat/deltachat-pages#172]
https://github.com/deltachat/deltachat-pages/blob/master/en/help.md

If Delta Chat doesn't have their own servers, does that mean it will drain my phone battery by constantly polling my email provider for updates?

**Comment by r10s** [comment]
Delta Chat keeps a socket open, this does not use much battery. stats may say something different, however, keep in mind that also the system keeps lots of sockets open, so there is no real "extra keep-wake or so just for delta".

in general, for user support, please use the support forum at https://support.delta.chat - this issue tracker is more about bugs and to coordinate changes.
