### ISSUE TITLE
Create Burner Account entry page

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#178]
For the upcoming Burner Account feature we need a nice entry page with graphics that explains what DC Burner Account is about.

**Comment by ghost** [comment]
Hi, is there already a concept, how the page is supposed to look like? 

Do we want to speak to a specified target group?

Is there a call to action?

Do we already have resources to point to, e.g. the server-side burner account code or so?

**Comment by hpk42** [comment]
The answers is currently mostly "no" to all questions.

**Comment by ghost** [comment]
Burner Accounts are not yet tackled - this will follow in the next weeks. It is not entirely clear yet how the feature will look like.

I will reopen the issue as soon as we have an idea what to write there :)
