### ISSUE TITLE
Translations on download Page are outdated

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#183]
https://delta.chat/en/download vs. https://delta.chat/de/download

The content is different

**Comment by hpk42** [comment]
On Wed, Oct 09, 2019 at 13:58 -0700, Simon Laux wrote:
> https://delta.chat/en/download vs. https://delta.chat/de/download
> 
> The content is different

Something easy to fix?  don't htink translators are reading this issue tracker here ...
and the german translation has been done by various people over time. 
So simply raising the issue does not gurantee anything ;)

**Comment by r10s** [comment]
i think the whole page is reworked meanwhile and this issue can be closed.
