### ISSUE TITLE
FAQ: Security of Delta Chat in comparison 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#190]
quote of the requests from the user:

   - discuss what is less secure than in PGP and in WhatsApp                                       
     when keys are validated via QR setup message? [pfs, ...]                                      
   - discuss metadata, you write                                                                   
     "Delta Chat even protects your metadata (who writes to whom?)"                                
     How? This data is still available for the mail providers                                      
     (which spreads this data more than on a centralized solution),                                
     as far I can see it does not encrypt headers or remove referrers,                             
     etc.                                                                                          
   - Differences between validated groups of 2 members vs.                                         
     1-1 chat with mutual validation.                                                              
   - compare also to pep (pretty easy privacy) and show it is the                                  
     better solution. I only did not install and test this app                                     
     cause of its permissions required on Android.

**Comment by missytake** [comment]
What are the differences between validated groups of 2 members vs. 1-1 chat with mutual validation?

Is validated == verified in this context?

**Comment by hpk42** [comment]
On Wed, Dec 11, 2019 at 04:17 -0800, missytake wrote:
> What are the differences between validated groups of 2 members vs. 1-1 chat with mutual validation?
> 
> Is validated == verified in this context?

yes, pretty sure validated was used as synonym for when we talk about "verified".

There are no "verified 1:1 chats", only verified groups.  

Note that groups can have two members which makes them look like 1:1 chats 
but you can add more people there.  You can't do that with 1:1 chats.

**Comment by adbenitez** [comment]
I think the difference in practical terms, is that a 1:1 chat with a verified contact, can become unverified, ex. the contact can change keys, you will see a message "setup changed for X"(or something like that) in the 1:1 chat, and everything will keep working as usual, so it is more dangerous, a verified group of 2 members will be the same as a 1:1 chat with a verified contact, BUT you have the extra security that the chat will only works if the contact is still verified, so you can't send anything by accident in a MITM attack, or that is what I think... not 100% sure, never used a verified group ;)

**Comment by hpk42** [comment]
@adbenitez yes, that's fitting.  Let me add:

The UX design of 1:1 chat is: always opportunistic. 
It is meant to allow people to communicate no matter if they change e-mail clients, devices,
setups etc.  If we started showing a "verification checkmark" then this would dilute
the image we want to project with the verification-checkmark. 

If a verification checkmark appears at the top of a chat this chat is 
invariably secure, and any breakage (cleartext or wrongly signed
messages etc.) will be flagged and such messages will not be shown 
in this chat.  Conversely, you can trust all messages in this verified-checkmark
chat to have not been read/altered by middle parties.

**Comment by missytake** [comment]
Thanks :) that was clear, I wrote something about it.
