### ISSUE TITLE
FAQ Section on Mail processing / Watch folder settings

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#191]

**Comment by ghost** [comment]
Is this about situations in which it makes sense to watch the DeltaChat/Sent/Inbox folders? Are the considerations documented somewhere, e.g. in an issue? I couldn't find one.

AFAIU:

* In which situations wouldn't you want to watch Inbox? I can't think of one.
* Why would you want to watch Sent, if "Copy to Self" is enabled anyway? What is the default setting for "copy to self"?
* Is turning off watching the DeltaChat folder good for saving bandwidth if you don't use multi-device?

**Comment by hpk42** [comment]
On Wed, Jan 15, 2020 at 16:07 +0000, M wrote:
> Is this about situations in which it makes sense to watch the DeltaChat/Sent/Inbox folders? Are the considerations documented somewhere, e.g. in an issue? I couldn't find one.
> 
> AFAIU:
> 
> * In which situations wouldn't you want to watch Inbox? I can't think of one.

It's not often done but some folks are currently playing with this: If 

a) you have a server-side rule to move all messages with Chat-Version header to DeltaChat folder 
b) use the default e-mail "Show classic emails = 'no, chats only'" policy 

then Delta Chat does not need to watch INBOX. 

> * Why would you want to watch Sent, if "Copy to Self" is enabled anyway? What is the default setting for "copy to self"?

Default setting for copy-to-self is "no" nowadays. One needs to enable it for multi-device settings
otherwise you don't see your own outgoing messages in the other device. Delta Chat *never* uploads
anything to the Sent folder because this would mean uploading a message twice (once through SMTP,
and once through IMAP to Sent folder). 

The only reason one wants to watch the Sent folder is if you are using another MUA (say Thunderbird) 
next to your Delta Chat app, and want your MUA to participate in chat conversations.  Now, that we
have Delta Chat Desktop pretty usable on all platforms, i would not recommend this -- and if one insists
on this setup, one could configure TB to also perform "bcc-self".

@r10s would you agree that offering to watch the Sent folder becomes increasingly superflous? 

> * Is turning off watching the DeltaChat folder good for saving bandwidth if you don't use multi-device?

That's currently a bit tricky maybe.  If you disable watch Delta Chat but have enabled "move chat messages
to DeltaChat folder" then, with the implementation as of January 2020, deleting a message from the
server will not work.  This is a bit subtle so it's recommended to only disable watching Delta Chat
if you also disable "move chat messages to DeltaChat". 

general note on watching: Every watched folder will generate some small amount of traffic as IMAP-IDLE is 
refreshed every 20-30 minutes, and every message that arrives there (if another device
or your own device moves messages there)

**Comment by adbenitez** [comment]
> > * In which situations wouldn't you want to watch Inbox? I can't think of one.
> 
> It's not often done but some folks are currently playing with this: If 
> 
> a) you have a server-side rule to move all messages with Chat-Version header to DeltaChat folder 
> b) use the default e-mail "Show classic emails = 'no, chats only'" policy 

c) Want to "disable" Delta Chat (stop receving messages) for some time


> @r10s would you agree that offering to watch the Sent folder becomes increasingly superflous? 

+1 on not watching Sent folder, using Delta Chat at the same time than a classic MUA isn't recommendable anyway


> > * Is turning off watching the DeltaChat folder good for saving bandwidth if you don't use multi-device?
> 
> That's currently a bit tricky maybe.  If you disable watch Delta Chat but have enabled "move chat messages
> to DeltaChat folder" then, with the implementation as of January 2020, deleting a message from the
> server will not work.  This is a bit subtle so it's recommended to only disable watching Delta Chat
> if you also disable "move chat messages to DeltaChat". 

oh! that is unfortunate! over here we disable the watch of DeltaChat folder, and it actually has an impact on slow network and data saving

**Comment by r10s** [comment]
> @r10s would you agree that offering to watch the Sent folder becomes increasingly superflous?

yip, i agree with that. currently, it is on by default, btw.
