### ISSUE TITLE
download page - make all downloads visible

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#192]
with nginx filesystem-index views
Will be accessed from a button on the download page, mainly to browse preview builds.

**Comment by ghost** [comment]
done: https://download.delta.chat/desktop/preview/

all other paths like https://download.delta.chat/desktop/ are restricted for now.

**Comment by ghost** [comment]
There is some way to sort the entries in the folder view/autoindex by date - that would be great in our case. Something like https://download.delta.chat/desktop/preview/&sort=created - @jnweiger do you remember how to do that?
