### ISSUE TITLE
remove netfily rests

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#195]
- [x] the netlify key
- [x] checks
- [x] the permission of netlify to this repo if it still exists

**Comment by ghost** [comment]
I removed the key and the permission.

What do you mean with checks?

**Comment by Simon-Laux** [comment]
when I do a pr the netlify check fail

**Comment by ghost** [comment]
Okay, it doesn't seem to appear anymore since I deleted their github hook.
