### ISSUE TITLE
readd YAML files to t-dance

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#210]
with the help of [yaml2po](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/api/convert.html#module-translate.convert.yaml2po) and po2yaml.

**Comment by r10s** [comment]
is this already done? there is a yml file on transifex.

**Comment by Simon-Laux** [comment]
yes, I forgot to close this

**Comment by r10s** [comment]
there were some changes done in https://github.com/deltachat/deltachat-pages/commit/61a87fef0e162018a6be64b33cd36ced5fe5562b but this did not really work and break the general translations. i commented the changes out in https://github.com/deltachat/deltachat-pages/pull/245 , however, in general, this seems to be tricky and i would not see this as a high priority. might be that we do not use .yml in the long run at all.

**Comment by Simon-Laux** [comment]
Ummm, the yaml part worked perfeclty fine for me.

> but this did not really work and break the general translations

you mean the missing values I recently fixed? (#238)
or the new part in the config file of tx that was previously untracked by git:
```
[delta-chat-pages.yml]
file_filter = translations/delta-chat-pages.yml/<lang>.yml
source_lang = en
type = YML
```
add this in the end of `.tx/config`, it should also be correct after pulling the config file from transifex

> however, in general, this seems to be tricky and i would not see this as a high priority. might be that we do not use .yml in the long run at all.

not agree at all, because I don't even understand what you problems do you mean?

**Comment by Simon-Laux** [comment]
Also for removing po sources from the repo and pulling them in when building will result in two ugly side effects:
- people that don't have access to our transifex can't build the website at all
- transifex pople can break the whole site generation at every time because they decide to translate liquid statements

weblate seems to have tests that can run before a translation is used, so maybe that's the way to go?

**Comment by r10s** [comment]
eg. the .tx/config file was missing from the repo at all, i just re-added it. also the paths for some ln-command was wrong.

**Comment by r10s** [comment]
> people that don't have access to our transifex can't build the website at all

why not? the website is made from the .md files, or?

the .po files are needed for transifex only. and if we want, we can also easily add some checks for bad code there. but we did not had problems in the past with translations breaking the website. not even when we had the animation with html/js on the homepage.

apart from that, i do not think that many ppl want to build our website :)

**Comment by Simon-Laux** [comment]
ah you're right, I just assumed we would gitignore the markdown files to -  then I take the points back, though we should add a `<!-- Generated file, please edit translation on transifex instead-->`

**Comment by r10s** [comment]
there are already DO NOT EDIT hint atop of every .md file outside the english-source-dir :)

**Comment by Simon-Laux** [comment]
right I forgot then everything is fine in that regard

**Comment by r10s** [comment]
> Ummm, the yaml part worked perfeclty fine for me.

@missytake as it seems no menu, footer or so are acatually translated, https://github.com/deltachat/deltachat-pages/issues/258, this needs to be targeted at some point - where was yaml2po or po2yaml ever called?

i commented out some non-working ln calls at https://github.com/deltachat/deltachat-pages/pull/245/files#diff-8277c559a21cd8de3e035e556ab924bd - not sure, maybe this was related, but what was this for?  i would expect the yaml2po/po2yaml calls where there are currently the txt2po/po2txt call are. if there are larger problems with yaml, however, we should drop this and go back to translated default-files as in the past - the layout is done in css anyway.

@missytake maybe you can also try the suggestion from @Simon-Laux above and try to add the yml to the .tx/config - might be that this does the job. together with a `cp` maybe (`ln` is always a bit tricky)

**Comment by Simon-Laux** [comment]
Yaml 2 po was not needed as we sync transifex directly with the yaml files

Am 19. Januar 2020 23:03:38 MEZ schrieb bjoern <notifications@github.com>:
>> Ummm, the yaml part worked perfeclty fine for me.
>
>@missytake as it seems no menu, footer or so are acatually translated,
>this needs to be targeted at some point - where was yaml2po or po2yaml
>ever called?
>
>i commented out some non-working ln calls at
>https://github.com/deltachat/deltachat-pages/pull/245/files#diff-8277c559a21cd8de3e035e556ab924bd
>- not sure, maybe this was related, but what was this for?  i would
>expect the yaml2po/po2yaml calls where there are currently the
>txt2po/po2txt call are. if there are larger problems with yaml,
>however, we should drop this and go back to translated default-files as
>in the past - the layout is done in css anyway.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-pages/issues/210#issuecomment-576052360

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by r10s** [comment]
yip, this is also what i finally understood.

so, the initial error was the deleted/ignored .tx file and a probably wrong ln command.
