### ISSUE TITLE
Privacy Policy only in German?

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-pages#213]
Hello,
I go to https://delta.chat/it/ then I click on the privacy policy button at the bottom of the page and it redirects on the german page https://delta.chat/de/gdpr-website.

If I change "de" with "it" to test if the page exists (https://delta.chat/it/gdpr-website) it doesn't work.

EDIT: maybe we've broken the redirect translating 

title: GDPR and Privacy
lang: en

to 

title: GDPR e Privacy
lang: it

Can you please explain me how this string should be translated?

**Comment by ghost** [comment]
Hm, the page only exists in german. So no wonder that it doesn't work.

You are probably looking for gdpr.md, not for gdpr-website.md.
* https://delta.chat/en/gdpr is about how the Delta Chat *app* handles GDPR
* https://delta.chat/de/gdpr-website is about how the Delta Chat *website* handles GDPR.

Not sure whether gdpr-website.md, which until now only exists in german, should be translated to other languages; it's only there for legal purposes. For the app it is important of course, but not sure how many people care about the legal details of visiting the website. If there are people who need this information available in their language, I hope they open an issue here, too.

**Comment by comradekingu** [comment]
@lefherz https://www.privacy-regulation.eu/en/article-6-lawfulness-of-processing-GDPR.htm
Legality is _all_ purposes. Insofar as morality goes, claiming it is only a legal matter fails too.
Edit: GDPR enforcement is a very crude instrument where only _one_ person needs to raise the issue,
consider it done.
The text should be made available for translation, vetted, and point to an authoritative German version where no other option is sound.
