### ISSUE TITLE
Move translations to Weblate

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-pages#215]
#210 is just one example of the pain transifex introduces. Multiple people recommended weblate to us. One contributor just created a weblate project of this repository at their instance and imported our strings into it.

I will look into it and migrate our translations to weblate if it does all the things we need.

**Comment by missytake** [comment]
@BoFFire I started by translating some strings on your instance - how can I create a PR to this repo from there?

**Comment by ghost** [comment]
Hi @missytake For now, we disabled the hook that allows to send PR directly. You have an option in the Weblate menu to download manually a single or a zipped batch file of your translations and make a PR manually :)
If you setup your own instance, you can push directly and pull from remote repo :)

**Comment by ghost** [comment]
@missytake By the way @nijel from Weblate can host the project for you on the community platform  https://hosted.weblate.org/ thus if you don't want setup your own :)

**Comment by missytake** [comment]
Ah, but we *love* self-hosting ;) I'll take a look first if I can figure it out myself :)

**Comment by r10s** [comment]
@BoFFire thank you very much for the hint to hosted.weblate.org - i think this sounds very interesting :)

however, just _now_, moving to weblate is not the main focus.

**Comment by r10s** [comment]
i think, if we give weblate a try, we should do that in a separate repository, maybe `deltachat-pages-new`, with a whole clone of this page. this should be visible online eg. at `https://new.delta.chat` - and if things work out, we can switch.

but we should not try to operate on this in the live-page.

**Comment by r10s** [comment]
~~closing this as there is no actionable item in this repo.~~
although there is no actionable item for this repo, we can keep it the issue open for now, just to make it more visible.

**Comment by hpk42** [comment]
For the record, it remains unclear to me what precise advantage we will get from moving to Weblate, compared to continuing with what currently works with transifex, even if not smoothly.   Such a move  comes with costs, i.e. we might loose translators; devs who currently know what to do need to learn new things etc.; there is need for reviewing and discussion etc.

**Comment by comradekingu** [comment]
@hpk42  What _currently works_ on Transifex is in keeping with the status quo of poor language. As my prior efforts to the contrary and the first-post attest to; it is a pain, minus me now not doing anything about it.

LibreOffice, FreeBSD and Fedora just started using Weblate.
The comparable user-base of Transifex for libre software is smaller, and is otherwise the same people with better hats on.

If you don't want do do any heavy lifting, use Hosted Weblate, wherein the best translators are already producing better results than ever seen with Transifex, and _especially_ for projects that come from there.

With Transifex the ability to take donations or sell Delta Chat in any capacity is lost, and the sudden realization of having to pay exorbitant licensing costs is gained.

**Comment by ghost** [comment]
Hi @hpk42,
Among the advantages :
- Translators can contribute using their mobile device. TransiThing is not offering mobile UI.
- Control : Get back the control
- You'll not loose translators, I'll bring my friends with me who translated altready variety of FLOSS projects. I can afford arabic and french alone [but not only me]
- Yes may be we're born to … learn and make efforts
- Weblate is … <3!

**Comment by BoFFire** [comment]
Hi @hpk42,
Among the advantages :
- Translators can contribute using their mobile device. TransiThing is not offering mobile UI.
- Control : Get back the control
- You'll not loose translators, I'll bring my friends with me who translated altready variety of FLOSS projects. I can afford arabic and french alone [but not only me]
- Yes may be we're born to … learn and make efforts
- Weblate is … <3!
