### ISSUE TITLE
The used app permissions should be explained in the FAQs

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#22]

**Comment by r10s** [comment]
Not sure eg. for what the _Phone_ permission is needed (IIRC it has sth. to do with recording voice message that should be stopped when there is an incoming call)

**Comment by ghost** [comment]
Permissions as far as I can see them in LineageOS 14.1:

- Camera
  - take pictures and videos
- Contacts
  - read your contacts
- Location
  - access approximate location (network location sources)
  - access precise location (GPS and network location sources)
- Microphone
  - record audio
- Storage
  - modify or delete the contents of your SD card
  - read the contents of your SD card
- Other app capabilities
  - change your audio settings
  - run at startup
  - control vibration
  - view network connections
  - prevent phone from sleeping
  - have full network access
  - view Wi-Fi connections
  - set wallpaper
  - ask to ignore battery optimisations

Camera, Contacts, Location, Microphone, and Storage can be easily disallowed (at least on LineageOS). All the "other app capabilities" permissions probably belong to the "Phone" permission scope?
