### ISSUE TITLE
Prepare Release-blog post Android Gplay + related project info

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#222]
collect images and news here already: 

- new UX features: profile-images, the device-chat and saved messages, picture:  https://user-images.githubusercontent.com/9800740/70670840-87505c80-1c7a-11ea-8f5c-2ff78338c9a6.jpg

- Android9 is better supported (notifications, 64bit) 

- the core library of deltachat is now completely written in Safe Rust (multi-month effort, started April 2019), and is using modern async libraries to perform IMAP and SMTP. It will still require stabilization but already it's running faster. Delta Chat is thus the first messenger app suite that has a full-Rust core.   

- RPGP, the e2e crypto engine used by all DC apps, got a security review (link to publishing the security report), no critical flaws found for DC's usage, and most (all?) other issues have been addressed. 

- note that F-droid is not yet available, we aim for it once the gplay release stabilizes. Unfortunately, the build-process and feedback loop speed of releasing on F-droid leaves much to be desired so we couldn't tackle it in conjunction with the current release.  You can install an apk directly from our website though.  
<add more news/infos here, also images/screenshots and pictures> 

Desktop and iOS could probably better reported in a separate blog post.

**Comment by ghost** [comment]
Awesome image - can we have that in english? The phone on the right is set in german. Only if it's not too much of a hassle.

When is the deadline for this?
