### ISSUE TITLE
CSS: make blogpost text width shorter

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-pages#226]
Right now, the text is pretty hard to read - the width is just a bit too long.

Those guidelines are quite good: https://socialtriggers.com/perfect-content-width/

**Comment by ghost** [comment]
With the latest blogposts, there was the practice, that there is always an image during the first one or two paragraphs - this is fitting for the recommended content width, according to the paragraph.

Blogpost authors should keep in mind that the first few lines are there to capture the attention of readers; following the format of AIDA - attention, interest, desire, action - is generally a good idea, if there are no good reasons against it. On the other hand we are not a marketing agency, so no need to take ourselves too seriously here, or to sell our soul to bullshit bingo best practices. Just try not to be boring.

end of excursus. closed :)

**Comment by hpk42** [comment]
One problem, btw, is that if you *start* a blog post paragraph with an "<img>" tag
that the summary for that post is empty on the https://delta.chat/en/blog page. 
Otherwise the the first sentence(s) are shown.  Ideally the summary page would
contain the images so not have a wall-of-text on the blog page. Not sure, how 
difficult that would be, though, so i didn't bring it up.

**Comment by ghost** [comment]
We figured out recently that the summary is not empty, if you don't leave an empty line between the <img> tag and the first paragraph :)

A perfect example is https://delta.chat/en/2019-12-18-google-play-store-release, which looks like this in the code:

```
<img src="../assets/blog/delta-xmas.jpg" width="150" style="float: left; margin: 10px;display: block;" /> 
**After months of hard work, we just started the [Delta Chat 1.0 releases series 
for the Google Play store](https://play.google.com/store/apps/details?id=chat.delta), 
with lots of tangible improvements. Thanks to the many developers, testers, translators and 
contributors who made this happen! See below for details on all the good changes.**
```

Showing the featured image on delta.chat/blog would be nice indeed. I'll open a separate issue for this.
