### ISSUE TITLE
MD5 / SHA-256 / GPG / fingerprints for all files provided

### ISSUE THREAD

**Issue by endbacher** [deltachat/deltachat-pages#229]
As data integrity and security is of increasing importance these days I'd like to suggest that 
- checksum files and/or
- fingerprints
are provided for all apps / programs that can be downloaded directly from the Delta Chat website (e.g. Linux, Windows, macOS) allowing the user to test integrity of downloaded copy in easy and reliable way. This information / checksum file should be provided either directly linked on the download page (https://delta.chat/de/download) or if not possible (or intended) linked near the download to right section on sub-page via https://delta.chat/de/verify_downloads#Windows or https://delta.chat/de/verify_downloads#macOS (links for illustration only!) to get to correct data with one click.

For the *.APK download one could think of storing the *.md5 files directly under https://download.delta.chat/android/

What do you think?

**Comment by r10s** [comment]
not sure what a fingerprint that can be downloaded from the same source as the apk is really worth. if an attacker could manage to change one file, it is pretty easy also to change the other. maybe it is useful if the file is downloaded from somewhere else and you trust https://delta.chat more than the original source - but then, why not download directly from https://delta.chat

compared to that, the already existent https://delta.chat/en/verify_downloads page seems to be  more useful as this allows to verify that the file is build with the given key. an attacker needs to infiltrate at least one - better all - developer machines plus the webpage, which seems to be much harder.

**Comment by r10s** [comment]
but sure, we should create some corresponding methods for the other 4 systems (ios/windown/macos/linux) as well.

**Comment by r10s** [comment]
closing stale issue no-one is working on. also it is at least partly targeted.
