### ISSUE TITLE
menus broken on some languages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#238]
eg. https://delta.chat/ca/ displays the footer as `| |` the translations for "Imprint" etc. are missing.

and for https://delta.chat/fr/ the download (!) link in the header is gone:

![Screen Shot 2020-01-08 at 22 21 23](https://user-images.githubusercontent.com/9800740/72017105-535e5c00-3265-11ea-8b01-5be4b765b7fa.png)

**Comment by ghost** [comment]
The title header is not translated in french: https://github.com/deltachat/deltachat-pages/blob/master/fr/download.po#L27

**Comment by ghost** [comment]
apart from that:

- spanish doesn't have a top menu at all, neither bottom menu
- neither NB
- neither PT
- neither UK.

**Comment by ghost** [comment]
Okay, the reason seems to be missing strings in https://github.com/deltachat/deltachat-pages/blob/master/_data/lang/fr.yml#L10 and the other languages in that folder.

**Comment by ghost** [comment]
Seems the strings just need to be translated... I'll ask around on the support forum for now. The chance to find people who speak those languages is the highest there.

**Comment by ghost** [comment]
The other problem is that `t-dance.sh pull` doesn't work for me right now, I think; either because of my local setup or because of #232. But I'll fix that next week

**Comment by Simon-Laux** [comment]
So either make a liquid function for getting the translation that falls back to english (what is not too straight forward and one reason I don't love jekyll),
add the englich string as fallback when doing tx pull
or asking the translators

**Comment by r10s** [comment]
i agree with @Simon-Laux , we should just fallback to english strings. if a fallback is not easily possible, we should maybe drop the key-value thingie.

the translations can be done sometime later. also, at least the translations for the menu are somewhere in the git history - before the key-value swtich, the menus were all complete.

**Comment by Simon-Laux** [comment]
even after they were complete, the connection to transifex is what broke them.

**Comment by r10s** [comment]
> the connection to transifex is what broke them.

iirc, the menu strings have never been on transifex at all. the template file were create "as a whole" by the translators.

but might come through the transifex-dance that does not support key-value-pairs yet, yes.
