### ISSUE TITLE
is sass really needed?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#239]
i try to get a feet into the latest changes of this repo and this sass thingie annoys me a bit.

imu, sass is a preprocessor that creates a .css file from some .scss files - adding some goodies as include and reusable values.

okay, but this comes at some cost.

- eg. it is no longer possible to peek at the css to see how things work and to simply adapt a style - this is how the generated css looks like https://delta.chat/assets/css/styles.css - and even if you figure out the node with some tools, you have to find the matching file - there is not just one scss file, there are severals.

- it is some work to install sass, it is not straight-forward, it is written in Dart (!), so you have to install that first which has some dependencies that have to match some special versions etc. of course, all solvable, but it takes some amount of work (i figured it out, though, but others maybe not yet)

- you cannot just edit the css and check the result in the browser, you have to run sass in between

- you have to learn how this relates to the live-config

- even if it may be simple, you have to learn some sass - whereas css is much more widely known. esp. as the page is typically maintained by devs doing other things most of the time and who do not have a main focus on web things.

given that we only have a tiny static page, i think this is a bit too much.

just to get an idea: this is the file we're talking about: https://github.com/deltachat/deltachat-pages/blob/f10a0c7cb93c48408acf9c407cc1be4ff46851f4/assets/css/base.css (version from some months ago)

sorry, for the rant, maybe i am just too old :)

**Comment by Simon-Laux** [comment]
> eg. it is no longer possible to peek at the css to see how things work and to simply adapt a style - this is how the generated css looks like https://delta.chat/assets/css/styles.css - and even if you figure out the node with some tools, you have to find the matching file - there is not just one scss file, there are severals.

use firefox's "Style Editor", it even reads a source map so it looks kinda like you're editing the original files. The minification of the css is for smaller size.

> it is some work to install sass, it is not straight-forward, it is written in Dart (!), so you have to install that first which has some dependencies that have to match some special versions etc. of course, all solvable, but it takes some amount of work (i figured it out, though, but others maybe not yet)

not correct, you just need to install jekyll - its build into jekyll, otherwise I would NOT have introduced it at all.

> you cannot just edit the css and check the result in the browser, you have to run sass in between

' '

> you have to learn how this relates to the live-config

what do you mean by live-config? your previous point?

> even if it may be simple, you have to learn some sass

no not at all, you can just write css. The point of the using sass is that we can split our code into logical parts, like global and download page.


> sorry, for the rant, maybe i am just too old :)

_/me thinks "Why do you don't properly look at it and then judge it with half-facts?"_
_/me ducks_

**Comment by r10s** [comment]
> not correct, you just need to install jekyll - its build into jekyll, otherwise I would NOT have introduced it at all.

i should have known that sooner. neither sass nor jekyll were installed on my machine - and i started installing sass. 

> we can split our code into logical parts, like global and download page

i know of the style-editor and also mentioned it, and i also know about minification and i know that the goal is splitting, reusing etc. but all for a tiny page? that's my main point. adapting the css is more complicated and not easier now - at least to me :)

> /me thinks "Why do you don't properly look at it and then judge it with half-facts?"

i just want to adapt a tiny css detail and i do not want to learn new things for that.
(i've learnt it now - so we can keep the stuff ;)

**Comment by r10s** [comment]
@Simon-Laux thanks for explaining, removing Dart again saves me 500mb :)

**Comment by Simon-Laux** [comment]
@r10s If your running low on diskspace remove the deltachat desktop logs https://github.com/deltachat/deltachat-desktop/issues/1321 
my logfolder is a gig in size :wink:

**Comment by r10s** [comment]
k, i know now that installing sass is easier than expected, however, i am still not sure if it is _needed_. but i will give it a try and i agree that we can close this discussion and go for some more important $things.

**Comment by Simon-Laux** [comment]
I did it just for the code cleanup sake to give it more structure. Its not an important point as you already mentioned.
