### ISSUE TITLE
translation push/pull not working

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#248]
needs some investigation, but the most recent changes on t-dance.sh (https://github.com/deltachat/deltachat-pages/pull/232/files#diff-8277c559a21cd8de3e035e556ab924bdR30) do not really work at least on my machine.

**Comment by r10s** [comment]
i am currently working on the local-help, so i will do a fix.

**Comment by comradekingu** [comment]
Transifex has this things where doing tx pull is unreliable.

**Comment by r10s** [comment]
> Transifex has this things where doing tx pull is unreliable.

might be, but in general, things worked fine, the problems came with the recent changes and are very basic (wrong path or so).

however, feel free to start using weblate in a copy of this repo eg. as described in https://github.com/deltachat/deltachat-pages/issues/215#issuecomment-573334266 - if things work out, we can switch over.

**Comment by r10s** [comment]
fixed by https://github.com/deltachat/deltachat-pages/pull/245
