### ISSUE TITLE
FAQ entry on differences to protonmail/tutanota/spike/criptext

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#250]
all of the four offer e2e encryption (spike maybe not even that) only for their respective users. All of them don't offer IMAP/SMTP and thus are technically no e-mail providers, just allow to receive and send messages to e-mail addresses (unencrypted).

**Comment by ghost** [comment]
for context: https://twitter.com/delta_chat/status/1216461676813455360 and https://twitter.com/delta_chat/status/1215978489137987585 and https://imaginair.es/@FredricT/103463889192725177 and...

**Comment by ghost** [comment]
Spike is not even a provider at all, right? And they do use IMAP, at least I can use it with a @testrun.org address over IMAP. Seems they are just a client. I would leave them out of this.

**Comment by r10s** [comment]
> Seems they are just a client.

well, the client is their server. so, if you login with testrun, eg. the password is saved on the spike server - and all trafic is routed over that. from the users point of view, however, delta and spike may look similar, both do "modern mail".

however, tbh, i've never really heard of spike or criptext outside our context, so, maybe there is no need to make them appearing more important as they're in fact. so, i think this is nothing for the "official faq" -  that also goes to the local help, is translated etc. but we can drop a forum not about that.
