### ISSUE TITLE
remove android-specific stuff from help.md

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#254]
help.md should be generic and should not refer to how things can be done on a specific os.

in general, this is true, however, the few "click-paths" should be removed or adapted.

**Comment by hpk42** [comment]
where would you put platform-specific help then?  
eg i think a section on background issues with ios/android would be good -- i keep answering according questions everywhere and would like to point to an FAQ section/entry.

**Comment by ghost** [comment]
I guess the reasoning behind is that we don't want to show Android-specific FAQs on Desktop etc.?

Can't we put the platform-specific help into specific categories? Right now we have `Groups`, `Encryption`, `Multi-Client`.... if we add categories for Android, Desktop, and iOS, it should be easy to filter out in the clients.

**Comment by r10s** [comment]
> if we add categories for Android, Desktop, and iOS, it should be easy to filter out in the clients.

i would not do that now. it raises the barriers for translation, add complexity etc. we currently hardly manage to keep the current faq up to date and translated. what i suggest is just a more neutral things, but i can do that, there are very few things to adapt.

**Comment by r10s** [comment]
> eg i think a section on background issues with ios/android would be good -- i keep answering according questions everywhere and would like to point to an FAQ section/entry.

sure, this can go to the normal help for now, just saying "on android this ... on desktop that ..." etc. i did not meant that there are no platform-specific things allowed, i just want to avoid them, where possible, eg. in "click-paths" - or say, on ios, do that, on android do this.

maybe the whole issue is a bit confusing, i will do a pr that make these this clear.

**Comment by ghost** [comment]
Hi, reviving this - do you still have the intention to make such a PR?

**Comment by r10s** [comment]
thanks for reminding, i have the intention, yes, just did not came to it :)

**Comment by r10s** [comment]
finally on that now, also upgrading this to a bug as some things are just wrong meanwhile.
