### ISSUE TITLE
category "desktop" - but no "android" nor "ios"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#256]
there is the category "desktop" in the forum - but not "android" nor "ios". are the some reasons for that? or is it just an error :)

**Comment by ghost** [comment]
You probably had a reason when you created it ;) https://support.delta.chat/t/about-the-desktop-category/103 maybe to give desktop developers a better reason to look into the forum?

Does the same reason apply to Android and iOS now?

Keep in mind that when we set up the forum, we wanted to have as few categories as possible. I'd like to keep it that way... but yeah.

Also, for questions like this we have the https://support.delta.chat/c/site-feedback/ category in the forum.

**Comment by Simon-Laux** [comment]
Yes this belongs to the site feedback category. Though I would say we should look into tagging then as many platform specific feature proposals turn out to be not so specific to one platform.

**Comment by Simon-Laux** [comment]
"moved" to https://support.delta.chat/t/new-forum-topics-about-mobile-platforms/750

**Comment by r10s** [comment]
> You probably had a reason when you created it ;)

not necessarily :)
