### ISSUE TITLE
menu entries are not translated

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#258]
for whatever reason, however, they were translated at some point.

the strings are already there, going some commits back in the history, there was one layout per language which was translated. we can copy the things from there maybe.

**Comment by Simon-Laux** [comment]
this is a translators thing, it needs to be put into transifex and the pulled via the script that works (on my laptop atleast).

**Comment by r10s** [comment]
well, it was all translated before, we could have preserved the existing translations, or?

**Comment by Simon-Laux** [comment]
If you want to add them manually, I preserved them until uploading english an connecting to transifex.
IMO we just need to do #210 and it will solve itself over time as the translators translate it.

**Comment by r10s** [comment]
my point is mainly, that we should be more careful with discarding existing translations. esp. if they are still needed literally the same way.

it is quite some work for the translators, it is annoying to do the same thing again, translators are not always available instantly, and it is ugly for the users - esp. when this affect the widely visible main menu which is english in all locales for some time.

just saying, i am not blaming someone. i also have to remind myself of that :)

**Comment by Simon-Laux** [comment]
I generaly agree, but not in this case.
10 words of which most languages hadn't even all translated are not that important - esspecialy if that would mean using the transifex webinterface to put them in, it would have probably taken me 30-45minutes. Not worth it IMHO.

Am 24. Januar 2020 21:16:54 MEZ schrieb bjoern <notifications@github.com>:
>my point is mainly, that we should be more careful with discarding
>existing translations. esp. if they are still needed literally the same
>way.
>
>if is quite some work for the translators, it is annoying to do the
>same thing again, translators are not always available instantly, and
>it is ugly for the users - esp. when this affect the widely visible
>main menu which is english in all locales for some time.
>
>just saying, i am not blaming someone. i also have to remind myself of
>that :)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-pages/issues/258#issuecomment-578284729

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by r10s** [comment]
> it would have probably taken me 30-45minutes.

that would have been worth the time, definitely :)

**Comment by r10s** [comment]
but, okay, we can close the issue and wait what will happen once #210 is done.
