### ISSUE TITLE
Gray out F-Droid / mark F-Droid especially

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#260]
Right now, F-Droid only has an outdated version of Delta Chat. 
Let's grey out the F-Droid choice (needs not be clickable) and put a note that F-Droid is coming, point to the issue where we work on this.  So we have gplay and APK download as primary choices for Android.

**Comment by r10s** [comment]
yip, esp. as F-Droid still has bugs that are related to group-splits, we should really discourage people from installing from F-Droid.

**Comment by Simon-Laux** [comment]
You can add the "soon" CSS class that makes it invisible like the other buttons that are on coming soon. We could either remove the style that makes "soon" invisible or use a new style all together for semi-new app providers.

Tip: try removing display:none from the soon class via your browsers inspector.

Am 18. Januar 2020 12:24:27 MEZ schrieb bjoern <notifications@github.com>:
>yip, esp. as f-droid still has bugs that are related to group-splits,
>we should really discourage ppl from installing from f-droid.
