### ISSUE TITLE
Show first image of a blog post on delta.chat/blog

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-pages#265]
Right now, delta.chat/blog shows the title and the first paragraph of a blogpost, together with a "Read on..." link to the actual blogpost:

![Screenshot_2020-01-20_16-18-14](https://user-images.githubusercontent.com/17278272/72737765-84f9f000-3ba0-11ea-91fe-7e5b644d7e92.png)

It would be really cool if we could show the featured image on this page as well, i.e. the first image of the post.

This was first brought up in #226 :)

**Comment by hpk42** [comment]
was doing a quick search -- maybe https://stackoverflow.com/questions/25463865/in-jekyll-how-do-i-grab-a-posts-first-image can be of help, might not be too hard after all.

**Comment by Simon-Laux** [comment]
I would go for the fontmatter solution
