### ISSUE TITLE
Is Delta Chat copylefted libre software?

### ISSUE THREAD

**Issue by comradekingu** [deltachat/deltachat-pages#270]
Hello, looking for something to use, see, change and share at will, with all. Somehow I am here.

In all likelihood first I went to https://signal.org and saw "After reading the code" "As an Open Source project" and then a link to GitHub.
Almost great. Seems like it is somehow fundamentally different from the plethora of chat clients out there.

Meanwhile at
https://delta.chat _Nuffins_

Lets scroll down here. _Nope._ But then:

> Please check get.delta.chat and the latest blog posts for information on current releases and events.

_I guess that is exactly the same info I already took in from the very categories up top it duplicates._

But there is promise of info in the Blog, so lets get millennial about this 1000 year project.
https://delta.chat/en/blog

I am finding a lot of spelling errors and a dwindling will to live. Pondering ending it right here.

Undeterred, focusing tenacious and unrelenting scrutiny onto [the FAQ](https://delta.chat/en/help) 
_Still, nuffins_.

(Impressive wall of text though, https://support.signal.org/hc/en and https://faq.whatsapp.com/en/general doesn't even have that.)

_OK, lets see here…_

> Delta Chat is like Telegram or Whatsapp but without the tracking or central control. Delta Chat does not need your phone number. Check out our

 [privacy statement](https://delta.chat/nb/gdpr).

_NNNNNNNNNNNNNNNNNNNNNuffins._

That isn't how "WhatsApp" is written, and there is a comma missing. Details. I have heard https://en.wikipedia.org/wiki/WhatsApp#Security_and_privacy about WhatsApp, and am somehow skeptic to something stating to be like it…

Theoretically I put my newfound and established fears aside and go to: https://delta.chat/nb/download

Well, to be fair it says "Source Code", albeit in the corner there. In further fairness that could be non-commercial.

![bilde](https://user-images.githubusercontent.com/13802408/73040341-80139580-3e59-11ea-95a1-64b8c767712e.png)

Gonna have to give that outdated Flatpak recommendation a pass.

Not sure I want to click that Google Play link further down either, because I am on the fence on this whole "the tracking or central control". Trust nobody I guess…
Don't really know what an APK is, because I've been to the FAQ…

OK, I am sure I would have asked if I knew to ask. Off to [Contribute](https://delta.chat/en/contribute)

"Delta Chat repositories where you can find the code for DeltaChat apps and this web site."

_I suppose, maybe?_

Landed in https://github.com/deltachat/ 

OK, clicking into https://github.com/deltachat/deltachat-pages at the bottom of which it says "Licensed GPLv3+, see the LICENSE file for details."

OK, clicking "[License](https://github.com/deltachat/deltachat-pages/blob/master/LICENSE)"

"The GNU General Public License is a free, copyleft license for
software and other kinds of works."

_Nice comma FSF, what does "free" qualify?_

> The licenses for most software and other practical works are designed
> to take away your freedom to share and change the works.  By contrast,
> the GNU General Public License is intended to guarantee your freedom to
> share and change all versions of a program--to make sure it remains free
> software for all its users.
> 

_And free software is?_

> When we speak of free software, we are referring to freedom, not
> price.
> 

"You" being? Man, I love this arbitration game, lets go back and read up just to make sure.

> 
> We, the Free Software Foundation, use the
> GNU General Public License for most of our software; it applies also to
> any other work released this way by its authors.  You can apply it to
> your programs, too.

_Most? I am sold, wow._

10 clicks in, exposed to plenty more red flags, and _wish_ I only read 10 times as much text as in this bug-report.

Bonus at the bottom of the Delta Chat pages repo:

> Remember: Form follows function, KISS. The site should be dead-simple.

Seems like the "simple" could be omitted.

**Comment by Simon-Laux** [comment]
You can do small PRs to fix that one problem/page at a time.
I agree that especially the landing page needs improvement.
I'm fixing the flathub outdated thing (as that information is deprecated, the thing is actually the same version as the downloads next to it (0.901.0).

you don't like GPL? or what is the ending part about?

**Comment by adbenitez** [comment]
agree that the main page should be clear about that Delta Chat is free software, recommended Delta Chat to someone in Mastodon and the first thing he said was something like "seems it is privative, doesn't find anything about the license in the main page"

**Comment by comradekingu** [comment]
@Simon-Laux The GPLv3+ is fine. The text in it however bears the mark of the FSF.

**Comment by hpk42** [comment]
let's find a succinct way to tell about Delta Chat being open-source/foss etc.  One of the problems is that there is no easy attribute. I don't want to spend half a sentence saying "free and open source software" and also don't want to use "foss" as a shortcut, it's only easily understood in particular circles. 

@comradekingu could you try to get more to the point in issues? It's a very long issue text. If it's "mention that Delta chat is an free/open source licensed project", it'd be easier to process/target. 
General complaints can go to the forum. Also you appear to have no good idea or empathy on how much people are working behind the scenes to deliver Delta chat on all platforms, with tons of languages, CI-systems, appstores, arrange funding and communicate with funders etc.  It's technically and socially complex.  

Yes, there are tons of things to be improved.  But everyone has a different focus and particular interest and approach. We on a daily basis get lots of feedback to process that is often marked as "super important". Please bear this in mind when opening issues, be succinct and suggest actionable items. Thanks :)

**Comment by Simon-Laux** [comment]
@comradekingu I like the long text-adventure-story style, but could you add todo-points/clear problems beneath it (in the future), that people don't read the long issue text and then need to guess what you could mean by it. (What are the concrete issues here?)

**Comment by comradekingu** [comment]
- Replace `Please check get.delta.chat and the latest blog posts for information on current releases and events.` on the [website landing page](https://delta.chat) with:

> Delta Chat is [copylefted](https://en.wikipedia.org/wiki/Copyleft) [libre software](https://en.wikipedia.org/wiki/Free_software).

along with, either

> Use, see, change and share at will, with all.


or

> [Use it](https://delta.chat/nb/download), [see how it is built](https://github.com/deltachat), [change](https://github.com/deltachat/deltachat-pages/blob/master/README.md) and [share it](https://www.gnu.org/licenses/quick-guide-gplv3.en.html) at will, with everyone.

(Similar to https://weblate.org and https://remmina.org)
