### ISSUE TITLE
C core library is still referrenced in contributing page

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#273]
Problem:
https://delta.chat/en/contribute#translations-and-bug-reports
![2020-01-24_17-23](https://user-images.githubusercontent.com/18725968/73084935-2d27f580-3ece-11ea-8c14-fc6681816c73.png)

Solution:
remove `C Core Library + Python Bindings Issues`-link from the contributing page.
And regenerate translations

**Comment by ghost** [comment]
I pushed & pulled the translations as well.
