### ISSUE TITLE
Mention iPads on get.delta.chat

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-pages#274]
We only speak about iPhones at get.delta.chat, although it works on iPads as well. Let's address all of our users here :) thanks @comradekingu for the idea.

I vote for `iOS (iPhones and iPads)`.

I will tackle this on Monday I guess, it's a oneliner after all

**Comment by Simon-Laux** [comment]
> I will tackle this on Monday I guess, it's a one liner after all

Done, we don't have much policy for the pages repo so you can make those kind of non controversial hotfixes directly without an issue IMO.
