### ISSUE TITLE
idea: speed up preview build through caching

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#276]
"Build the site in the jekyll/builder container" is slow and the most time in it is spend fetching dependencies. Maybe we can somehow cache those dependencies to speed up the process even more?

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows

**Comment by ghost** [comment]
I guess we could cache /var/lib/docker to reuse the docker container.

**Comment by r10s** [comment]
closing stale issue no-one seems to take care of. maybe also things are fast enough :)
