### ISSUE TITLE
Show F-Droid logo again on get.delta.chat

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-pages#284]
F-Droid offers version 1.1.2 now! We can finally show it on the website again.

It's not yet updated on https://f-droid.org/packages/com.b44t.messenger/, maybe we should wait for this before merging.

**Comment by r10s** [comment]
wow! good job everyone 🥇 

or those who cannot wait until the index is updated, here's the direct download:
https://f-droid.org/repo/com.b44t.messenger_574.apk

**Comment by ghost** [comment]
In the store it's already available :) just the F-Droid website still shows the old version.
