### ISSUE TITLE
Fix reverse DNS for testrun.org

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#287]
as reported today from jnsp on IRC: 

>  Hi there, i just noticed that I cannot receive mail from
> delta-identity@testrun.org, because there is no reverse DNS entry
> configured for the IPv6 address it is sending mail from
> (2a01:4f8:c0c:4da3::2)

> Should be set to "testrun.org". And testrun.org should have an AAAA
> entry with 2a01:4f8:c0c:4da3::2 as the host supports v6 (if enabled in
> the webserver config).

**Comment by missytake** [comment]
fixed it.
