### ISSUE TITLE
remove or update 'References'

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#289]
the references in the footer are outdated, the last update is about a year old, in between, there were several posts on heise, also heise print, dpa and more.

we should either remove the list completely or update it more frequently.

currently, it looks as if the project has no references since a year or so.

**Comment by ghost** [comment]
Updating it more frequently makes more sense, I think. It is important for trust. The crosslinks might be useful for the undecipherable workings of SEO as well.

**Comment by r10s** [comment]
just came over https://retoeugster.ch/blog/deltachat/
