### ISSUE TITLE
FAQ: do the double ticks in group messages mean that everyone has read my message?

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-pages#290]
"Can I ask you a question? In groups the double ticks mean that everyone has read the message? 🤔"

Not sure which is the current behavior:

- [ ] double ticks appear if one person has read the message
- [x] double ticks appear if >= 50% of the recipients have read the message
- [ ] double ticks appear if all recipients have read the message

I'm also not sure what happens if some group members have disabled read receipts.

**Comment by Simon-Laux** [comment]
~~I guess it's double ticks appear if one person has read the message~~

**Comment by r10s** [comment]
double ticks in groups appear when the majority has read the message, i've written down some thoughts on that some years ago, https://delta.chat/en/2017-07-06-read-receipts-and-social-pressure
