### ISSUE TITLE
Disable page generation on github

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#3]
As I understand Netlify, there is no need for pages on github to be enabled. So, I think we can disable them sooner or later.

This also avoids _duplicate content_ at https://r10s.github.io/deltachat-pages/ - or isn't that an issue nowadays?

**Comment by kskarthik** [comment]
AFAIK github doesn't generate pages until you opt for travis-ci integration for repo

**Comment by r10s** [comment]
This has nothing to do with travis-ci.

If you select a source at "Settings / GitHub Pages", Github deploys pages to `https://<username>.github.io/<repository-name>/` - https://r10s.github.io/deltachat-pages/ for us.

![bildschirmfoto vom 2017-05-04 10-10-37](https://cloud.githubusercontent.com/assets/9800740/25695103/17f94600-30b2-11e7-94c6-f32f74d58fb6.png)

I think, this does not really hurt (maybe no good for SEO), however, it just seems to be not neccessary as we use Netlify to deploy the pages to https://delta.chat

**Comment by kskarthik** [comment]
Dont select github pages(optional?). Netlify will take care of that.

**Comment by kskarthik** [comment]
Choosing custom domain option below will override it I think

**Comment by r10s** [comment]
I do not think, _Github pages_ has sth. to do with _Netlify_.

Both do the same things:

- listen to pull requests made to a given repository
- if there is one, they make a copy of the repository to a folder, that is accessible via http/https (however, some things are converted before, eg. by Jekyll)

The custom domain is not much more as an alias to the (unattractive) github.io domain.

**Comment by r10s** [comment]
Disabled. Deploying via Netlify still works as expected.
