### ISSUE TITLE
Do a check before tx push - are we on the master branch?

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-pages#302]
Calling `tools/t-dance.sh push` is quite dangerous and can destroy the work of our translators, if it's done from an outdated branch.

We should check whether it's executed on the master branch. It would be also good to check whether it's up to date with origin/master.

**Comment by r10s** [comment]
this should do the job: https://stackoverflow.com/a/37890564

**Comment by ghost** [comment]
Unfortunately, the automated push job fails now.

**Comment by r10s** [comment]
@lefherz can you please check for the reason and do a fix on that?

**Comment by ghost** [comment]
On it.

**Comment by r10s** [comment]
great!

**Comment by ghost** [comment]
Hm, the github action runs on a detached HEAD:

```
HEAD
HEAD detached at e8a4142
nothing to commit, working tree clean
```

We could checkout & pull master in the GitHub action? Or write an alternative function which overrides the check, and which is not to be called manually?

**Comment by r10s** [comment]
i'd say we should checkout and pull. the `tx push` must also not run on some detached head.

however, if all that's gets too complicated, maybe renaming `./tools/t-dance push` to `./tools/t-dance push--do-this-only-from-master` would probably also give some protection. it is not so easy to type in and not so easy to confuse with `./tools/t-dance pull`

**Comment by ghost** [comment]
Why not both :D

**Comment by ghost** [comment]
The action ran well: https://github.com/deltachat/deltachat-pages/runs/464868550?check_suite_focus=true

Finally :)

**Comment by r10s** [comment]
cool! thanks for taking care!
