### ISSUE TITLE
Beta Testing on GPlay -> Get it on Google Play

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-pages#319]
get.delta.chat still speaks about "Beta Testing on Google Play". This is not necessary anymore.

**Comment by ghost** [comment]
We don't need to wait with this until the app leaves the actual beta track on GPlay :)

**Comment by r10s** [comment]
leaving beta-track, however, is also planned these days, https://github.com/deltachat/deltachat-android/issues/1262 , but, yes, no need to sync these things. it is just some wording, in fact, we're not beta since beginning of this year or so :)
