### ISSUE TITLE
blog overview is pretty large

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#321]
the [blog overview](https://delta.chat/en/blog) is meanwhile pretty large, currently about **7mb** - and growing.

the large size was introduced by showing the images in the blogposts at https://github.com/deltachat/deltachat-pages/pull/282 - before that, the overview was only about **30kb**.

we can handle this issue by 

1. adding a paging thingie, jekyll seems to support things there, i never dived into that

2. showing only the first 10-or-so messages and load the next 10-or-so or so messages when scrolling down (as in the forum)

3. load images only if they come to view

4. show images only for the first 10-or-so messages - this would also mitigate the problem that several images are a bit weird.

further alternatives would be to remove the images or to ignore the issue. or to use more optimized images - but after all experience, this won't work in practice, creating a blog post is already hard enough :) maybe the overview can create thumbnails automatically, but this is some additional effort.

1.+2. would sacrifice easy on-site-search and 2.+3. would require js afaik, so a not-so-good-solution

i think 4. should be pretty easy to do, just had a look, checking the index in the look at https://github.com/deltachat/deltachat-pages/blob/master/_includes/blog.html#L2 should do the job. probably a one-line-change.

**Comment by pabzm** [comment]
For pagination with jekyll 4.0, apparently jekyll-paginate-v2 3.0 could be used easily.

Add this to the Gemfile:
```gemfile
gem "jekyll-paginate-v2', '~> 3.0'
```

And follow this example: https://github.com/sverrirs/jekyll-paginate-v2/tree/master/examples/01-typicalblog

**Comment by r10s** [comment]
yip, however, i personally do not want to dive into that now, it will be some hours of work. also as this would require to revisit/hand-optimize the remaining posts/images, like i've done for the first ones in #322 

so, i think the issue solved by #322 ([preview](https://staging.delta.chat/322/en/blog)) - and we can add paging later - if we really want to :)
