### ISSUE TITLE
ipad is not detected correctly on get.delta.chat

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#338]
"macOs" is shown as recommended system on ipads with ios13 - where it should be iOS, of course.

**Comment by Simon-Laux** [comment]
looks like its also a bug on apples side: https://forums.developer.apple.com/thread/119186
They use the same User agent for macOS and IpadOS.

**Comment by r10s** [comment]
> looks like its also a bug on apples side [...]

i fear, it is not a bug, it is a feature: https://webkit.org/blog/9674/new-webkit-features-in-safari-13/
