### ISSUE TITLE
Fix jekyll deployment

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-pages#348]
In https://github.com/deltachat/deltachat-pages/commit/2f19cd1ee39a5966782d48943a6839291f4967ff I hotfixed the jekyll deployment, as the jekyll/builder:latest docker container failed to build our page (e.g. https://github.com/deltachat/deltachat-pages/actions/runs/103692192)

The fix was using an old jekyll version which is not updated anymore, and therefore won't suddenly break - not an optimal solution. Investigating the real error and fixing it could be worth the time.

**Comment by ghost** [comment]
related: https://github.com/envygeeks/jekyll-docker/issues/272

**Comment by r10s** [comment]
is this still an issue?

**Comment by Simon-Laux** [comment]
still relevant see https://github.com/deltachat/deltachat-pages/blob/master/.github/workflows/jekyll-master.yml#L20
Now the question is whether we want to say at version 3 or whether we want to go back to master. the former is probably more stable for us for now.

**Comment by r10s** [comment]
k, thank s for details.

unless there are real problems with staying at the current version, i suggest to close this issue.
