### ISSUE TITLE
Preview blog entries on twitter and other social medai

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#350]
I think our web page generation could use some hints to allow social media to show a preview.  @missytake @Simon-Laux @pabzm do you happen to have an idea? 

![preview-twitter](https://user-images.githubusercontent.com/73579/83048879-940b1600-a04a-11ea-8ac5-c2bacae18bb8.png)

**Comment by Simon-Laux** [comment]
There are meta tags for this, `<meta property="og:image" content="image.png">` is one of them but I don't know which ones are supported on twitter.

**Comment by missytake** [comment]
Sounds good, though I'm used to wordpress plugins handling it ;) it should be easy enough though, I hope to get to it in June.

**Comment by r10s** [comment]
just had a quick look, the `og:` thingie is used by facebook (and probably others), twitter uses a separate `twitter:card` system, also through the same `<meta>` tags, however, it seems to picks up `og:` as well under some conditions (https://css-tricks.com/essential-meta-tags-social-media/, https://medium.com/@dinojoaocosta/how-to-make-twitter-preview-your-website-links-5b20db98ac4f)

for the latter, there is even a validator at https://cards-dev.twitter.com/validator - in fact, it looks pretty bad for delta chat pages.

i will try to do a pr.
