### ISSUE TITLE
502 Bad Gateway for mailing-list subscription

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#351]
the mailing list subscription as linked on the "contribute" page, https://lists.codespeak.net/postorius/lists/delta.codespeak.net/, is not working.

instead `502 Bad Gateway` is shown.

**Comment by missytake** [comment]
I wrote a mail to the admins list.

**Comment by r10s** [comment]
great, thanks!

**Comment by missytake** [comment]
Hm, I got a mailer daemon response... something is very broken there.

**Comment by missytake** [comment]
works again.

**Comment by r10s** [comment]
great!
