### ISSUE TITLE
document self-hosting instructions

### ISSUE THREAD

**Issue by khimaros** [deltachat/deltachat-pages#384]
it would be helpful to have recommendations for smtp/imap servers to use with DeltaChat, and perhaps configuration examples: i've had some success with dovecot + postfix.

**Comment by r10s** [comment]
we have https://github.com/deltachat/provider-db - do you mean sth. like that?

in general, we use bug trackers mainly for bugs and for things some people actually have subscribed to - feature requests and general discussions should go to https://support.delta.chat

**Comment by khimaros** [comment]
I'm referring to self-hosted options rather than existing providers. In other words, if the user wants to run their own mail server, what's the best configuration to use for Delta Chat compatibility?

I could take a stab at this, as my current setup seems to be working pretty well, but it required a bit of trial and error.

**Comment by r10s** [comment]
maybe just add a forum-entry for now? we have a "Howto" section that could be filled more :) https://support.delta.chat/c/howto/8

**Comment by r10s** [comment]
closing, no actionable item for deltachat-pages.
