### ISSUE TITLE
document outbound port connectivity requirements

### ISSUE THREAD

**Issue by khimaros** [deltachat/deltachat-pages#385]
some network providers [block](https://www.cox.com/residential/support/internet-ports-blocked-or-restricted-by-cox.html) outbound port 143 connections which makes DeltaChat less viable for those users. it would be helpful to document outbound port requirements to make this clearer to newcomers.

**Comment by r10s** [comment]
closing stale issue, also, not sure what really to do on that here - network providers supporting "standard" email ports also support Delta Chat - "special" ports may cause issues in both cases.

are there comparable documentations for network providers eg. on Thunderbird?
