### ISSUE TITLE
add new languages to ngnix config

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#401]
with #399 merged, we have now 4 more languages: `zh_CN`, `tr`, `id` and `gl`

the languages are selectable by the footer, however, it would be great it is also selected automatically by the server when the user arrives with eg. a Chinese browser.

for the other languages, this is done somehow via via https://github.com/deltachat/sysadmin/blob/master/delta.chat/delta.chat

**Comment by r10s** [comment]
with https://github.com/deltachat/deltachat-pages/pull/422 also `cs` should be added.

**Comment by missytake** [comment]
I fixed it.

For documentation, see https://github.com/deltachat/sysadmin/commit/de46e281b9c9b1e9c0eaf3050af6aba3e9f69126

**Comment by r10s** [comment]
yeah! thanks for fixing, @missytake!
