### ISSUE TITLE
blog about security reviews

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#406]
2 were done ...

**Comment by missytake** [comment]
- finish https://github.com/deltachat/bg-deltachat/blob/master/security-reviews/First_security_review.md and https://github.com/deltachat/bg-deltachat/blob/master/security-reviews/Second_security_review.md, summarize them in blogpost
- link to PDFs in blogpost

What kind of outline do we want? what kind of tone? @hpk42 said he wants to start writing this blogpost soon-ish, and already made up his mind about these things.

**Comment by r10s** [comment]
done with https://delta.chat/en/2023-03-27-third-independent-security-audit :)
