### ISSUE TITLE
Watching the Inbox makes sense to turn off, if you have...

### ISSUE THREAD

**Issue by thenktor** [deltachat/deltachat-pages#440]
Hi,

IMHO the documentation about "Why can I choose not to watch the Inbox?" is missing something. I'm using a Mailcow mail server, that has a sieve filter to move all DeltaChat mails to the DeltaChat folder (see: https://mailcow.email/2021/01/14/back-to-the-future-with-delta-chat/ and https://github.com/mailcow/mailcow-dockerized/commit/3dece1a05c97c1b989b432bd0609710fef91e95c)

So I've turned off to watch the inbox. But this is only fine, as long as the chat partners are using the DeltaChat client, too. If an answer comes from a usual mail client, it of course does not have the Chat-Version header and therefore stays in the inbox. It never reaches DeltaChat then.

Therefore the "Watching the Inbox makes sense to turn off, if you have..." list should also have an entry:

- if you don't want to chat with non DeltaChat users

**Comment by ghost** [comment]
I opened a PR which pretty much says this - is this what you mean?

**Comment by thenktor** [comment]
Exactly :+1:

**Comment by r10s** [comment]
closing, see https://github.com/deltachat/deltachat-pages/pull/447#pullrequestreview-678353604 for reasoning
