### ISSUE TITLE
provide howtos for using setup-contact QR codes on web pages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#458]
that may require downloadable/printable QR codes and maybe [an option to de-activate/re-activate existing codes](https://github.com/deltachat/deltachat-core-rust/issues/2511).

so, there may be some other steps needed to be done before actually creating a webpage, and faq- and/or a forum-entry.

**Comment by hpk42** [comment]
we meanwhile have the QR-code-howto here https://support.delta.chat/t/how-to-quickly-establish-secure-chats-with-qr-codes/1968 and @Yettte is bound to incorporate some feedback and then close this issue.

**Comment by Yettte** [comment]
Incorporated feedback in QR code how to.
