### ISSUE TITLE
Put the logo on the Download page

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-pages#460]
We got the feedback that there should be a logo on the download page: https://social.tchncs.de/@mray/106185401661663580

I agree with this feedback.

We could put a headline "Get Delta Chat for your device!" + Logo on the right to the top of the page.

**Comment by r10s** [comment]
currently, we do not have the logo on most pages.

maybe better add the logo somewhere to the header bar, as eg. signal does.

**Comment by rosano** [comment]
Resolved with #586
