### ISSUE TITLE
Protonmail Bridge for SMTP/IMAP

### ISSUE THREAD

**Issue by fossdd** [deltachat/deltachat-pages#466]
I found that Protonmail offers a tool called [Protonmail Bridge](https://protonmail.com/bridge/) which should bridge the Protonmail API.

I don't know if that works, but may you can add it to `help.md`

**Comment by r10s** [comment]
yip, this is known - and the information is already shown to the user on login and at https://providers.delta.chat/protonmail .

adding detailed information about special providers to the general faq seems to be too much.

**Comment by fossdd** [comment]
Ah okay, agree. It's just that it looks more like it completly doesn't work with Protonmail.

**Comment by r10s** [comment]
we can maybe tune down the statement in the help, sth, as "... they do not offer receiving mails via unrestricted IMAP." however, in a way it is correct already now, protonmail-server as such does not offer IMAP, this needs the bridge. also, it does still not work for android and ios, it only works for paying desktop users that do not want to go for multi-device. that is pretty broken :)

**Comment by fossdd** [comment]
Yes. That would be nice

**Comment by r10s** [comment]
i think this is sufficiently handled
