### ISSUE TITLE
blog about upcoming 1.22

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#467]
the device messages and the changelog can be used as sources of inspirations :)

**Comment by missytake** [comment]
Is this the first release where all platforms get the same version number and get released at the same time?

**Comment by r10s** [comment]
> Is this the first release where all platforms get the same version number 

we did that before, eg. on 1.20, https://delta.chat/en/2021-05-05-email-compat

> and get released at the same time?

well, this is not the main goal, we do phased releases even on one platform.

also, syncing releases between platforms is quite some effort - and it may be even unadvantageous if bugs pop up that are not caught in comparable small testing group.
