### ISSUE TITLE
New references for Delta Chat Website

### ISSUE THREAD

**Issue by Yettte** [deltachat/deltachat-pages#484]
A very recent positive mentioning of Delta Chat comes from Ubuntubuzz. Would be nice to have it on our website as well :)

https://www.ubuntubuzz.com/2021/09/delta-chat-overview-and-installation.html

**Comment by missytake** [comment]
I have another one, too: https://blog.desdelinux.net/delta-chat-1-22-ya-fue-liberado-y-estas-son-sus-novedades/

**Comment by missytake** [comment]
https://relejek.ml/public/blog/app-review-delta-chat/

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-pages/commit/a50c1795ab74c263a610e781b3265d89078e086f
