### ISSUE TITLE
uppercase in GDPR-blogpost may result in 404

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#494]
the uppercase-characters in https://delta.chat/en/2021-11-10-blog-GDPR are unfortunate, even if following some rfc and specs, there are apps out there that lowercase urls, for whatever reason.

as an example that directly appeared to me, there is the feedbot, that gave me the url https://delta.chat/en/2021-11-10-blog-gdpr - which is not working. sure, we could fix feedbot, however, in practise, there will be more issues like that, so in general, these URLs should be avoided.

as the uppercase-URL is already "out", however, we should keep that and handle this by a redirect.

~~unfortunately, i have no idea (or forgot) about how to create redirects here - iirc, this also was an issue for some short-urls, that only @missytake could create :)~~  
found sth: redirects are at https://github.com/deltachat/sysadmin/blob/master/delta.chat/delta.chat, however, i do not want to edit without more detailed knowing ...

(this issue is just about fixing the current URL, however, it would be great if creation of forwarding could also be documented)

**Comment by missytake** [comment]
I added `rewrite /en/2021-11-10-blog-gdpr /en/2021-11-10-blog-GDPR permanent;` to the nginx config and reloaded the page; can you confirm that it works now?

**Comment by missytake** [comment]
I documented it here: https://github.com/deltachat/sysadmin/blob/master/delta.chat/delta.chat#L154

**Comment by r10s** [comment]
yeah, it works now :) thanks a lot!

**Comment by r10s** [comment]
> I documented it here: https://github.com/deltachat/sysadmin/blob/master/delta.chat/delta.chat#L154

is there something more to do than adding this line? or is a pr to the sysadmin  repo sufficient? i assume somehow the server needs to reload config or whatever :)

**Comment by missytake** [comment]
Sorry, apparently it was 2 AM when I did that. Actually the useful documentation is here: https://github.com/deltachat/sysadmin/blob/master/delta.chat/README.md#redirect

**Comment by r10s** [comment]
thanks. with "documentation" i was thinking more about some hint in the README.md here is this repo, so that blog authors and page editors can add a redirect on their own as needed. however, as there is some login to the server needed, it is a bit more complicated than just editing a file here, so, things are probably fine :)

thanks a lot for taking care!
