### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-pages#510]
It's time to rework the FAQ again, there have been a lot of changes, especially on the desktop client.

- [ ] is this still up-to-date? https://delta.chat/en/help#which-messages-do-appear-in-delta-chat
- [ ] the security review mentioned in https://delta.chat/en/help#what-is-a-verified-group-why-is-it-experimental has happened
- [x] are there any updates to https://delta.chat/en/help#how-are-delta-chat-developments-funded ?
- [ ] It would be wise to link to https://support.delta.chat/t/import-backup-to-ios/1628 in https://delta.chat/en/help#can-i-use-delta-chat-on-multiple-devices-at-the-same-time
- [ ] is the delta chat data encrypted on my device?
- [ ] how private are private apps? (webxdc trust model)
- [ ] where can I get private apps?
- [ ] how can I create my own private apps?
- [ ] how can I change my account? (AEAP)
- [x] drop a line about Archived chats, cmp. https://github.com/deltachat/deltachat-core-rust/pull/3184
- [ ] what is the "recently seen" dot and what doe it mean? (eg. it does no tracking, in contrast to whatsapp etc.)
- [ ] what happens if I turn on auto-delete messages from server?
- [ ] what happens if I turn on auto-delete messages from client?

**Comment by Yettte** [comment]
"are there any updates to https://delta.chat/en/help#how-are-delta-chat-developments-funded ?" This is a good point, also exists here: #520
