### ISSUE TITLE
Some accessibility issues with the site

### ISSUE THREAD

**Issue by johanbove** [deltachat/deltachat-pages#513]
- Operating System (Linux/Mac/Windows/iOS/Android): All
- Delta Chat Version: DeltaChat-pages latest
- Expected behavior: Better Lighthouse reporting score, current score is [only 71 for Accessibility](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fdelta.chat%2Fen%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext)
- Actual behavior: n/a
- Steps to reproduce the problem: Run an accessibility checker on the site's home page
- Screenshots: 
![Screenshot 2022-01-13 235538](https://user-images.githubusercontent.com/922765/149421861-96d00398-4610-41c0-b453-2dbf4302fd40.png)
![Screenshot 2022-01-13 235625](https://user-images.githubusercontent.com/922765/149421904-67e4a55a-310e-4054-b677-07f673e76391.png)

- Logs: [See LightHouse report](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fdelta.chat%2Fen%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext)

**Comment by johanbove** [comment]
Cool. The score has improved significantly. (not perfect yet though - will check)

![grafik](https://user-images.githubusercontent.com/922765/154675291-3a631134-3c90-41bc-bc8a-be6746848631.png)

**Comment by johanbove** [comment]
But since we're "in the green" now - I'll close the issue.

**Comment by missytake** [comment]
Thanks for taking care!

**Comment by hpk42** [comment]
thanks for caring!
