### ISSUE TITLE
oversimplificationing

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-pages#53]
Too much oversimplificationing easily removes important information, relating and background.

https://delta.chat/de/delta-macht-chatten-besser
https://delta.chat/de/david-gegen-goliath

**Comment by r10s** [comment]
these post have the character of a blog entry (eg. they're not updated), therefore i moved them to the blog:

https://delta.chat/en/2017-05-31-delta-makes-chatting-better

IIRC, the other post was more or less equal.

However, maybe we should add a redirect using:
https://www.netlify.com/docs/redirects/

However, these days i have no time for it :)

**Comment by testbird** [comment]
Ok, restructuring is fine of couse. :)
(Was getting negative reply about not working links in a message.)
The other text was even better in providing the motivation to start coding.

**Comment by r10s** [comment]
Okay, the old links work again and even the missing legacy text is added to the multi-lingual post now.

**Comment by testbird** [comment]
Many thanks, everything is much appreciated!

**Comment by r10s** [comment]
you're welcome.
