### ISSUE TITLE
https://delta.chat/ results to a 403 Fobidden error

### ISSUE THREAD

**Issue by Mikaela** [deltachat/deltachat-pages#541]
- Operating System (Linux/Mac/Windows/iOS/Android): Fedora 36 and iOS 15,5
- Delta Chat Version: N/A
- Expected behavior: Navigating to https://delta.chat/ redirects me to https://delta.chat/en/
- Actual behavior: 403 Forbidden
- Steps to reproduce the problem: Navigate to https://delta.chat/ on either Firefox 102.0b3 or Safari on iOS 15.5
- Screenshots:

![kuva](https://user-images.githubusercontent.com/831184/171930712-658eb261-203e-4b50-99d9-f4941eff3690.png)

- Logs: N/A or I don't have access to the server to see them.

**Comment by Mikaela** [comment]
I am unable to reproduce these two issues using a clean Firefox profile through `firefox --ProfileManager`, but I have no idea how to clean up my iOS to not result to this issue. I also doubt being the only one encountering these.

**Comment by r10s** [comment]
thanks for reporting, closing this issue in favour of the more general #618

**Comment by missytake** [comment]
@Mikaela it should work now! Can you retry?

**Comment by Mikaela** [comment]
Yes, seems to work. Thanks.
