### ISSUE TITLE
delta.chat/en/ has a big download button and suggests get.delta.chat which are 404 errors

### ISSUE THREAD

**Issue by Mikaela** [deltachat/deltachat-pages#542]
- Operating System (Linux/Mac/Windows/iOS/Android): Fedora 36 and iOS 15.5
- Delta Chat Version: N/A
- Expected behavior: Pressing the download links on https://delta.chat/en gives me the download options sending me to https://delta.chat/en/download (like the Download link on top of the page)
- Actual behavior: I am given a 404 error.
- Steps to reproduce the problem: Navigate to https://delta.chat/en on either Firefox 102.0b3 or Safari on iOS 15.5, scroll to bottom of page and press download or get.delta.chat
- Screenshots:

* ![kuva](https://user-images.githubusercontent.com/831184/171931200-daa70569-9abe-459d-bb6b-df11a7a77df3.png)
   * The problematic links
 * ![Supposed download page](https://user-images.githubusercontent.com/831184/171931263-c3d0a451-4c1a-4ea9-b787-efd8a93ecf8f.png)
   * The link target. Additionally clicking the link results to #541.

- Logs: N/A or I don't have access to the server to see them.

**Comment by Mikaela** [comment]
I am unable to reproduce these two issues using a clean Firefox profile through `firefox --ProfileManager`, but I have no idea how to clean up my iOS to not result to this issue. I also doubt being the only one encountering these.

**Comment by r10s** [comment]
weird. i cannot reproduce that either.

cc @missytake - maybe you have an idea? maybe some strange redirect conditions? maybe related to the weird double-adding of `/en/` on 404's? (eg. if you try to open <https://delta.chat/en/does-not-exist>

**Comment by missytake** [comment]
Hm. @Mikaela which languages are configured in your browsers?

**Comment by Mikaela** [comment]
In Firefox apparently only Finnish which I think is the default upon downloading from https://releases.mozilla.org/pub/firefox/releases/102.0b3/linux-x86_64/fi/

In iOS I assume it uses the system languages which are in this order: Finnish, English (Ireland), Esperanto, Swedish, Espaňol and Russian.

**Comment by Mikaela** [comment]
Yesterday I noticed this was reported in the forum already with more details

* https://support.delta.chat/t/website-not-working-with-certain-accept-language-header/2043?u=aminda

**Comment by r10s** [comment]
i think, this was only a side-effect of fixed https://github.com/deltachat/deltachat-pages/issues/618 - if not, please open a fresh issue with detailed information
