### ISSUE TITLE
Formatting/Export of EPPD comparison export is suboptimal

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#552]
just recommended https://delta.chat/assets/blog/eppd-comparison-final.pdf in the forum, but I noticed that the pdf export/ formatting is suboptimal, as you don't know which row is what in the later pager and also the speedtests stand there without any real explanation

**Comment by missytake** [comment]
"We published our measurement tool [eppdperf on github](https://github.com/deltachat/eppdperf) and intend to improve it further. In that repository you also find the raw data underlying our overview table." - I think we should just show the first three pages there - if anyone is interested in the details, they can go to the repository and look at the data in .ods format.

The data doesn't fit on an A4 page, trying to display that in a pdf file is pointless I think (and at least my libreoffice doesn't easily allow exporting it in different formats).

I'll open a PR :)
