### ISSUE TITLE
Account deletion link

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#555]
should link to FAQ entry explaining that we have no accounts

maybe this could help some people. what do you think?

**Comment by missytake** [comment]
I don't fully understand - where should this link be? In the clients?

**Comment by Simon-Laux** [comment]
on the website, in clients could also be an idea. this is related to a recent email we got addressed to the support email asking us to delete their userdata. saying they could find nothing on the website.
