### ISSUE TITLE
homepage is outdated in other languages than English

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#556]
the start site layout.

**Comment by missytake** [comment]
oh, thanks for the heads up.

**Comment by r10s** [comment]
it's a bit on-purpose as the source was changed frequently at some point, however, yes, things are settled now and we should update.

**Comment by missytake** [comment]
How was this prevented technically? How can we update the pages?

**Comment by missytake** [comment]
Usually the translations would have been pushed there, right?

**Comment by r10s** [comment]
no, usually, nothing happens when the english source is updated;

updated translation sources are pushed manually (at least this is my state of knowledge here :)

EDIT: i pulled recent translations, [commited them](https://github.com/deltachat/deltachat-pages/commit/bf670addabd6ab2bc672b0dc34bc81b5e75d5ae0) and ran `./tools/t-dance push--do-this-only-from-master` - let's give the translators some days for translation and pull the updates afterwards (things that are still untranslated then will be english)

**Comment by r10s** [comment]
someone (probably me :) ran `./tools/t-dance push--do-this-only-from-master` already some time ago, so with the recent pull, things should up to date for all languages - english, if in doubt.

**Comment by missytake** [comment]
> someone (probably me :) ran `./tools/t-dance push--do-this-only-from-master` already some time ago, so with the recent pull, things should up to date for all languages - english, if in doubt.

we have a CI job which does that every time new commits are pushed to master: https://github.com/deltachat/deltachat-pages/blob/master/.github/workflows/tx-push.yml

So I doubt this is what was wrong so far?

**Comment by missytake** [comment]
Hm, apparently that didn't happen in 3 weeks, maybe that was indeed the case.

**Comment by missytake** [comment]
in any case, now it's the new text, though it isn't translated yet.

**Comment by r10s** [comment]
> though it isn't translated yet.

it is translated for german, dutch, italian, polish. all others are not 100% and partly or event mostly english, yes.

**Comment by r10s** [comment]
> So I doubt this is what was wrong so far?

ahh, i was not aware (or forgot) that there is a ci action for it. probably okay, we usually discuss new pages in prs, so when it is merged to master, it should be already settled a bit.

what is not in ci seems `t-dance pull` - for the reason that we want to have a final view on the created pages - it happens not so infrequently that some glitches happen, eg. translated links or so. otoh, delaying translations is also an issue, so, maybe it would be okay to do this in ci as well - which, however, may lead to broken pages that are not noticed for some time unless some user complains.

as a compromise, maybe ci can create a pr with the result of `t-dance pull` every some days? then we would have a chance to roughly check the changes and even preview the page.
