### ISSUE TITLE
add infos about onion email service usage

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-pages#558]
- Desktop has socks proxy settings 
- android and iOS work in conjunction with orbot in VPN mode
- We should describe which settings need to be adapted during account setup or - if an existing account needs to be changed - in the account settings screen 
- We could add links to the official tor apps

**Comment by r10s** [comment]
for orbot, there are some information in the forum already: https://support.delta.chat/t/socks4-5-and-http-proxy-support/162/8 - maybe, this is the better start to collect things in general

closing stale issue here, everyone who's interested and can do things please do a pr on this repo or just add sth. to the forum
