### ISSUE TITLE
FAQ section on experimental features

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-pages#565]
- [ ] How does the experimental database encryption work? 
- [x] What is a verified group? Why is it experimental?
- [ ] How Can I Change My Account to a Different E-Mail Address? (AEAP)
- [ ] Can I share my location with my chat partners?
- [ ] Does Delta Chat support Audio/Video Calls?
- [x] Why can I choose not to watch the Inbox?
- [ ] What are broadcast lists and how do they work?

All these features are experimental right now - there should be a section explaining how they work.

**Comment by Simon-Laux** [comment]
> What are broadcast lists and how do they work?

mention that they are unencrypted by nature because they use BCC, which means including keys for all recipients breaks the "anonymity" of the recipient list.

**Comment by missytake** [comment]
I wrote a paragraph on it.
