### ISSUE TITLE
FAQ: drop some words about multi account

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#568]
afaik, it is not even mentioned. we should at least say, that it exist (it is not obvious on all systems, which is fine, as not needed from the very start. but if one eventually reads trough FAQ, one should get the information that there is sth. as multi account :)

**Comment by missytake** [comment]
It is mentioned here: https://delta.chat/en/help#multiclient

**Comment by r10s** [comment]
i read only about multi-device/multi-client (using the same account on different devices) there, not about multi-account (using several accounts on the same device). but maybe i also have overseen sth - can you point directly to the line or so?

**Comment by missytake** [comment]
Sorry, you are right, I misread your request^^
