### ISSUE TITLE
FAQ: Create tips section with information about some "hidden" functions

### ISSUE THREAD

**Issue by EchedelleLR** [deltachat/deltachat-pages#570]
*I write this issue until a proper pull request is made from my side*

As spoken at https://github.com/deltachat/deltachat-android/issues/2414, a tips section could be added into the FAQ for "hidden" yet useful functions in Delta Chat.

The idea would start creating the section and adding information about the image previews for images added to the chatbox before being sent.

**Comment by r10s** [comment]
as this issue got a bit stale: 

we already have https://support.delta.chat/c/howto/8 for tipps & tricks and "hidden functions", i think, we can just use that - this also has the advantage that it is much easier to get sth. in there.
