### ISSUE TITLE
Image and text alignment fails for screen widths up to 640 pixels

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-pages#596]
- Expected behavior:
For screen widths up to 640 pixels, the text of a blog article is aligned to the bottom margin of an image, but not positioned in the same line, and the image itself is aligned to the left margin:
![grafik](https://user-images.githubusercontent.com/51095533/209429301-5bce9ce1-75da-4424-ac38-6f38f7594a3b.png)

- Actual behavior:
For screen widths up to 640 pixels, the text of a blog article is aligned to the right margin of an image, and the image itself is not aligned to the left margin:
![grafik](https://user-images.githubusercontent.com/51095533/209429252-025292da-69d3-4e78-9c1d-af461e8546ed.png)

- Steps to reproduce the problem:
-- Load a blog article that includes an image in your browser, e.g. https://delta.chat/en/2022-12-15-uidevjob .

- Screenshots:
See above.

- Logs:
N/A.

**Comment by r10s** [comment]
i just analyzed the CSS a bit and tried to catch the gist: the issue is hugely mitigated by just inserting a linebreak, see https://github.com/deltachat/deltachat-pages/pull/672
