### ISSUE TITLE
tx push throws error

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-pages#605]
We just added https://delta.chat/en/serverguide, which is nice, but pushing it to transifex for translation doesn't work.

`README.md` says that we need to do the following:

```
### Add a new page

- create the source as `en/<name>.md`

- modify `tools/.tx/config` - add a section for the new page
  modify `tools/t-dance.sh` - add your page to `sfiles` variable

- run `./tools/t-dance push--do-this-only-from-master`
```

Step 1 and 2 were done in #604, but the last command throws an error:

## Expected Behavior

If I run `./tools/t-dance push--do-this-only-from-master`, it compiles po sources out of the markdown files, and pushes them to transifex.com with the `tx` CLI tool, where they can be translated.

## Actual Behavior

First of all, if I run `./tools/t-dance push--do-this-only-from-master`, it throws an error, because the file is named `t-dance.sh` not `t-dance`. This should be fixed in `README.md`. But even when I run `./tools/t-dance.sh push--do-this-only-from-master` it doesn't work:

```
user@xubuntu20:~/git/deltachat-pages/tools master 127 ± ./t-dance.sh push--do-this-only-from-master
mkdir: cannot create directory ‘translations/delta-chat-pages.yml’: File exists
master
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
tx ERROR: not enough values to unpack (expected 2, got 1)
```

The mkdir error gets ignored with a `|| true` clause, but still maybe the error message should be redirected to `/dev/null` - I had to find out by debugging that this wasn't the problem. Especially if you only run `t-dance.sh create-po-sources`, then only this error is thrown, even though *actually* everything went fine.

But the tx error at the bottom is a problem. Has tx changed completely? We try to run `tx push -s` in the script. But when I try to run `tx --help` locally, it doesn't even show the `-s` option:

```
$ tx --help
usage: tx [--version] [-d] [-q] [--root ROOT_DIR] [--traceback] [--disable-colors] [--cacert /path/to/ca-cert-bundle-file] [command]

This is the Transifex command line client which allows you to manage your translations locally and sync them with the master Transifex server. If you'd like to check the available commands issue `tx help` or if you just want help with
a specific command issue `tx help command`

positional arguments:
  command               TX command

options:
  --version             show program's version number and exit
  -d, --debug           enable debug messages
  -q, --quiet           don't print status messages to stdout
  --root ROOT_DIR       change root directory (default is cwd)
  --traceback           print full traceback on exceptions
  --disable-colors      disable colors in the output of commands
  --cacert /path/to/ca-cert-bundle-file
                        set path to CA certificate bundle file
```

**Comment by r10s** [comment]
you need to use the new `tx` cli tool written in go, python tool is sunset, see https://github.com/deltachat/deltachat-android/pull/2434.

output of `tx --help` looks like the following:

```
NAME:
   tx - A new cli application

USAGE:
   tx [global options] command [command options] [arguments...]

VERSION:
   1.6.4

COMMANDS:
   migrate, mg  Migrate legacy configuration.
   merge        tx merge [options] [resource_id]
   push         tx push [options] [resource_id...]
   pull         tx pull [options] [resource_id...]
   add, a       Add a resource in config. Use no arguments for an interactive mode.
   init         tx init
   delete       tx delete [options] [resource_id...]
   update       Update the `tx` application if there is a newer version
   status       tx status [resource_id...]
   help, h      Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --root-config FILE          Root configuration from FILE
   --config FILE, -c FILE      Load configuration from FILE
   --token value, -t value     The api token to use [$TX_TOKEN]
   --hostname value, -H value  The API hostname [$TX_HOSTNAME]
   --cacert value              Path to CA certificate bundle file [$TX_CACERT]
   --help, -h                  show help (default: false)
   --version, -v               print the version (default: false)
```

the old python tool stopped working, see

**Comment by r10s** [comment]
however, before pushing more strings to transifex, let's first resolve https://github.com/deltachat/deltachat-pages/pull/599

**Comment by missytake** [comment]
Hm, how did the old tx tool save the API token? Now it's passed via an `TX_TOKEN` environment variable afaict, we should make up something for this.

**Comment by missytake** [comment]
`README.md` is not up to date yet, it still talks about the old tx tool. I can bring it up to date when I get the new tx running

**Comment by r10s** [comment]
k, i think, we can close this, it is mainly about confusion with old/new tool, i just pushed new strings to transifex, this works as expected. please open a new issue if things are still not working.
