### ISSUE TITLE
Translations missing for front page

### ISSUE THREAD

**Issue by rosano** [deltachat/deltachat-pages#633]
Seems like the following localizations are showing English for the main page. I think at least French and Portuguese would have a translation…

https://delta.chat/cs/
https://delta.chat/fr/
https://delta.chat/pt/
https://delta.chat/ru/
https://delta.chat/sk/

Wondering if this happened with #631?

**Comment by rosano** [comment]
Hmm seems like it happened last year with https://github.com/deltachat/deltachat-pages/commit/bf670addabd6ab2bc672b0dc34bc81b5e75d5ae0 – what happened there?

**Comment by rosano** [comment]
The string was 'created' last year, but I feel like it was already there.

![Screenshot 2023-03-29 at 11-26-55 Delta Chat Website Transifex Editor](https://user-images.githubusercontent.com/1680612/228426781-06c987a2-6973-4d08-8865-981eec1a52ea.png)

**Comment by r10s** [comment]
i think, the french and other page were just never translated.

> Wondering if this happened with https://github.com/deltachat/deltachat-pages/pull/631?

this seems not to be the case,
see wayback machine:

https://web.archive.org/web/20220817021809/https://delta.chat/fr/ (before homepage update)

https://web.archive.org/web/20230315231137/https://delta.chat/fr/ (after homepage update, but before fixing things yesterday)

all snapshots in between also show the untranslated page.

looking at transifex confirms this, there is no history or so.

so, i think, from the view of deltachat-pages, everything is working as expected.
