### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-pages#64]
There is a file called LICENSE in the repository which contains the GPLv3 but in the individual files and the readme nothing refers to it. Therefore, it is not clear if the GPL is applicable.

Also, if I use the CSS and just change the colors, will it be enough to simply add the LICENSE file and a GPL header? I mean, everyone can download it with some developer tools.

Reference: https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by r10s** [comment]
thank you for the note, i have added a link to LICENSE in README.md, see https://github.com/deltachat/deltachat-pages/commit/dcec5ddedcc5a7e8fc282ae75980fa31674a1cae .

i think, adding "copying permission statements" atop of each file is not easily possible and/or inconvenient; many files are images and also markdown files have no compatible way to add such notes. for css we could do so, however, having such a note only in a minority of files, people may come to the conclusion that the other files are licensed another way...

so, i think, we can leave the rest it as it is -  the linked howto says "Each file's copying permission statement (also called the license notice) should come right after its copyright notices". well - _should_ - not even _SHOULD_ :)

**Comment by Hocuri** [comment]
Very good, thank you.

**Comment by r10s** [comment]
Thank you, too :)
