### ISSUE TITLE
untranslatable paragraph

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#67]
as @Sebek05 figured out, there is a single string in help.md that cannot be translated.

it's the first paragraph after https://delta.chat/en/help#can-i-re-use-by-existing-private-key :

although translated in the .po file, the resulting .md file does not contain the correct string, eg. in german:
https://delta.chat/de/help#kann-ich-meinen-bestehenden-privaten-schl%C3%BCssel-weiterverwenden

i have no idea for the reason, we use po2txt, maybe here are people around with more background on this tool.

maybe this bug is related to https://github.com/translate/translate/issues/1601 ?

**Comment by adbenitez** [comment]
little typo it is: https://delta.chat/en/help#can-i-re-use-my-existing-private-key
s/by/my/

**Comment by r10s** [comment]
great, didn't noticed this that time.

however, seems as if the problem is solved, the paragraph is translated at least on the german page.
