### ISSUE TITLE
delete-previews github actions fails 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#675]
![image](https://github.com/deltachat/deltachat-pages/assets/73579/bfc7f971-f329-45bc-a29b-2d5e9f137c37)
turning all PRs red since yesterday or so.

**Comment by link2xt** [comment]
Made a fix: https://github.com/deltachat/deltachat-pages/commit/6c9f9f7cf27ff0187f52ab0a6468b2f8191d7da7
We will see if it works once some next PR is merged.

**Comment by missytake** [comment]
Another idea is to delete all folders with preview builds which are older than a month. This could happen with the delete preview cronjob, which is already executed regularly: https://github.com/deltachat/sysadmin/tree/master/delta.chat#github-action-to-copy-it-to-correct-location

If you want to look at the preview page of a stale PR which has not been updated for a month, you can rebase it to generate a new preview build. Rebasing is probably a good idea in such a case anyway.

**Comment by link2xt** [comment]
I have removed this workflow completely in https://github.com/deltachat/deltachat-pages/commit/bc6e3338ccfffd15bf52c0d9e2081dc7d7393023 because the "fix" caused issue #679 

This workflow is going to be replaced by a server cronjob.
