### ISSUE TITLE
more CI issues: /var/www/html/staging gets deleted automatically every once in a while

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-pages#679]
For example https://github.com/deltachat/deltachat-pages/actions/runs/5058473282/jobs/9078632290 failed because of this.

Workaround: It's fixed by running this on page:

```
sudo mkdir /var/www/html/staging
sudo chown jekyll:jekyll /var/www/html/staging/
```

But after a while (half an hour or so) it reappears. So I think it's some github action or cronjob deleting one directory too much.

**Comment by missytake** [comment]
...of course we could just add a cronjob to re-create this directory every 10 minutes :clown_face:

**Comment by link2xt** [comment]
At least now the folder is there and was not removed even after rerunning the "deploy master branch" workflow on the last commit: https://github.com/deltachat/deltachat-pages/actions/runs/5059316869/jobs/9205658619

The only suspicious CI I found is this:
https://github.com/deltachat/deltachat-pages/blob/33da4d3b1b3adf6f53826feb2213d5d4a67c1c42/.github/workflows/delete-preview.yml#L30

Maybe somehow `${{ steps.prepare.outputs.prid }}` is an empty string, would it result in deleting `staging`?

**Comment by missytake** [comment]
> Maybe somehow `${{ steps.prepare.outputs.prid }}` is an empty string, would it result in deleting `staging`?

Yes, this seems to be it; the replacement index.html isn't uploaded to `staging/$prid/`, but just to `staging/`. And then, staging gets deleted.

**Comment by link2xt** [comment]
I have removed this buggy workflow: https://github.com/deltachat/deltachat-pages/commit/bc6e3338ccfffd15bf52c0d9e2081dc7d7393023
