### ISSUE TITLE
Use names of languages in their native script

### ISSUE THREAD

**Issue by farooqkz** [deltachat/deltachat-pages#695]
For someone who knows English alphabets and language codes(or can guess), it's easy to find the version of DeltaChat website for their own language. But for someone who knows only their mother tongue, it's impossible. Therefore, I suggest writing name of languages in their native script in the bottom of the website.

**Comment by r10s** [comment]
if we want to go that way, all native names are at https://github.com/deltachat/deltachat-android/blob/master/res/values/arrays.xml#L7 (mostly confirmed by the corresponding translators, this is not always that easy to figure out :)

however, it will take more room,  more typical thing would be a language dropdown eg. in the upper right corner, but maybe we can do a first step without

**Comment by farooqkz** [comment]
Yeah I agree writing them this way will take too much space. Maybe use country flags instead?  A dropdown is not a good idea IMO people who don't understand English, won't realize it's for changing the language.

**Comment by r10s** [comment]
> Maybe use country flags instead?

languages do not always match borders; there is quite some antipathy to country flags among contributors :)

however, i did a [pr](https://github.com/deltachat/deltachat-pages/pull/696), it does not look bad, i think it is okay and quite some improvement.

there is a **preview at https://staging.delta.chat/696/**

> A dropdown is not a good idea IMO people who don't understand English, won't realize it's for changing the language.

that's a point, indeed. thanks a lot for the careful considerations!

**Comment by farooqkz** [comment]
> > Maybe use country flags instead?
> 
> languages do not always match borders; there is quite some antipathy to country flags among contributors :)

Yeah I know. You can link multiple flags to the same language.

**Comment by farooqkz** [comment]
> there is a **preview at https://staging.delta.chat/696/**

Doesn't look very bad but not good either. I suggest putting language links in a `p` and limiting its width to about 50vw. Unless it's on mobile which then it should have full width.

**Comment by r10s** [comment]
> Doesn't look very bad but not good either. 

that's already an improvement i'd say :)

> I suggest putting language links in a p and limiting its width to about 50vw. Unless it's on mobile which then it should have full width.

i added a commit,  https://staging.delta.chat/696/ should be updated soon (force-reload may be required)

**Comment by farooqkz** [comment]
Looks much better. These dots all at the end look ugly on 360x760 res:

![image](https://github.com/deltachat/deltachat-pages/assets/15038218/ed946bf2-d82f-4df1-a138-6c26f203d5f2)

And also 240x320:

![image](https://github.com/deltachat/deltachat-pages/assets/15038218/4fad8e55-5155-4fdb-9ca2-849e00b41e86)

**Comment by r10s** [comment]
not sure if we can easily do much about the dots. also, these super-narrow views are quite rare nowadays, so in practise, there are fewer dots. i think, it is okay :)
