### ISSUE TITLE
serverguide: change all occurences of "optional" to "recommended"

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-pages#704]
Some headlines say "optional: " at the moment, even though we really recommend it.

Let's be a bit more paternalistic about this ;) if we wouldn't recommend it, it wouldn't be part of the guide.

**Comment by ralphtheninja** [comment]
Maybe move the reverse dns settings to the section https://delta.chat/en/serverguide#create-dns-entries ? Maybe also change the `Name` column values to the full host names? E.g. `mail.example.org` instead of just `mail`.
