### ISSUE TITLE
blog about typical e-mail concerns?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#74]
sometime eg. when the verified groups are final, i would suggest, someone should add a blog post about typical e-mail concerns as:

- lots of meta data leakage -> modern e-mail implementations encrypt the subject and other headers (memoryhole) -> the receiver may get the ip-address of the sender vs. the typical walled garden server has all ip-addresses and the social graph of all people communicating there

- pgp vs. forward secrecy vs. attaching the identity to a phone number

- e-mail is slow - but maybe fast enough

- e-mail was not created for messaging (so what :)

...

**Comment by veit** [comment]
@r10s: Would it be possible to measure the performance in a realistic way compared to other implementations?

**Comment by r10s** [comment]
@veit what do you mean with "other implementation" - other e-mail programs or other messengers? 

for delta chat, in the message info, the sending time and the receiving time is shown, typically, 1 ~ 3 seconds if IMAP-PUSH and the servers are working properly.

conventional messengers are typically faster as, i think, through centralization, less computers are involved. 

however, i have also seen messages from Telegram, who claim to "deliver messages faster than any other application." [[source]](https://telegram.org/#why-switch-to-Telegram) hanging around for minutes. so, there are issues with other services as well.

so, the question is: is it relevant to the typical user is a message needs 0.5 seconds or 1.5 seconds? or even 3 seconds? and how can we argue.

**Comment by veit** [comment]
@r10s Thank you for the informations. With other implementations I meant other messengers. And if the transfer of images and other files is much slower, it may affect the chat. Therefore, some measurements would be helpful for the assessment.

**Comment by r10s** [comment]
afaik the typical e-mail-delay is independent of images/text/whatever; when the first bytes are transferred the following are no longer delayed. so, for larger files, the difference might be even _less_ significant.

**Comment by veit** [comment]
Great, thanks for the info.
