### ISSUE TITLE
remove stale `en/changelog` file from server (it is not in repo)

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#795]
there is an old android changelog file on the server - https://delta.chat/en/changelog - the file is not in use nor updated and the corresponding `.md` file was long removed - however, the `.html` file is still on the server.

this is especially an issue as this changelog file pops up when searching for “delta chat changelog” (reported by https://support.delta.chat/t/update-the-changelog-page-please/2908 - i can confirm that for duckduckgo as well as for google)

we can just delete the file, SEO-wise, it is maybe better to do a redirect and/or change the content of the HTML-file to 

> a changelog overview is now available at https://delta.chat/en/download#changelogs

@missytake can you have a look at that?

**Comment by missytake** [comment]
I deleted it.

**Comment by missytake** [comment]
Then I thought about it a second time and created a redirect :upside_down_face: https://github.com/deltachat/sysadmin/commit/6a8cd977c78281d8046b219857f018246c015bd1

**Comment by r10s** [comment]
thanks a lot!
