### ISSUE TITLE
Cant log in via github account 

### ISSUE THREAD

**Issue by tompatulpan** [deltachat/deltachat-pages#797]
The login to the forum via github account has not worked for me for over a week now.

1. Going to: https://support.delta.chat/
2. Log in
3. Log in via Github
4. Recieves a 404-page

This has worked perfectly for years until now!?

**Comment by missytake** [comment]
Yes, I'm surprised as well. We are working on it: https://github.com/deltachat/sysadmin/issues/139

(you probably can't view this issue, as it is in a private repository.)

**Comment by hagenest** [comment]
Log in through GitHub should now be working again :) Thank you for the report!

**Comment by tompatulpan** [comment]
yeah, its working now. Thanks!
