### ISSUE TITLE
demote downloads of Android and Desktop-release-files because of missing automatic upgrades

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#823]
We should not recommend as primary options any downloads that do not provide automatic updates.
So i suggest to demote

- [ ] .exe 
- [ ] .rpm
- [ ] .deb 
- [ ] .tar.gz
- [ ] .AppImage
- [ ] apk 
- [ ] apklis (because it's outdated) 
- [ ] dmg

to not have images but be listed in the fine-print.

**Comment by Simon-Laux** [comment]
> to not have images but be listed in the fine-print.

maybe rather collapsed behind under a `<detail>` tag with the summary "Other downloads without automatic updates"

And remove / comment out apklis as long it is outdated.

**Comment by Simon-Laux** [comment]
I had this in the project as  "pages: nudge people to the stores because they provide auto updates", I replaced that draft card with this issue.
