### ISSUE TITLE
add a section about onboarding

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#836]
we should describe briefly what is going on, for deeper reasonings etc. we'll probably link to a blog post that will come with 1.46 as well

the onboarding section is then probably linked from the welcome pages; in general, however, it makes sense to target this issue comparable late, currently too many things are under construction and not 100% settled.

**Comment by hpk42** [comment]
If i am not mistaken, then https://github.com/deltachat/deltachat-pages/pull/838 resolved this by introcuing the "what is chatmail" option to be shown from "explore other options" in the create-profile screen.
