### ISSUE TITLE
Provide a community alternative chatmail onboarding page

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#837]
There are three public alternatives to nine.testrun.org: 

- https://mehl.cloud
- https://mailchat.pl
- https://bcc.chat

We need an entry page listing these (plus link to source for setting up your own), that we can link from get.delta.chat and the upcoming 1.46 in-app onboarding process but it needs to be be made clear that these instances are not run by delta chat folks, and nine's privacy policy does not apply. 

I think each alternative should get links to fediverse operators and a small background para.

**Comment by kermoshina** [comment]
Are there discussions about a possible UI for this? E.g. for Mastodon they include several filtering options: by topic / by language / etc, but there are only a few chatmail instances now so may be filtering can come later. In Jabber it looks much more sober, with just a few details in form of a table. 

I think for us it could be something in between
![Jabber public servers](https://github.com/deltachat/deltachat-pages/assets/16879492/1e74cadc-5846-4cc9-b3e4-53f2d663e499)
![Mastodon public servers](https://github.com/deltachat/deltachat-pages/assets/16879492/650c9f40-e7dc-4b30-b4ab-24e0de89bf81)
