### ISSUE TITLE
Infinite redirects happen for non existing pages

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-pages#848]
go to https://delta.chat/foobar and you will be redirected to https://delta.chat/de/de/de/foobar etc.

same for https://delta.chat/chatmail/ instead of https://delta.chat/chatmail 

previous discussion: #618

**Comment by r10s** [comment]
@missytake iirc, we tried fixing that some years ago already, without success, or we decided that there were larger fishes to get. but i agree, it is pretty annoying, i also come over that regularly, would be great if you can have a second look, sth. is wrong with our redirects

**Comment by nicodh** [comment]
On which web server are the pages hosted? The redirects have to be configured on that server I guess...

**Comment by r10s** [comment]
hm, the README points wrt language-redirects to https://github.com/deltachat/sysadmin/blob/master/page/delta.chat/delta.chat - but that seems outdated - @missytake will know better :)

**Comment by r10s** [comment]
clicking around, configuration seems to be at https://github.com/deltachat/sysadmin/blob/master/page/config/nginx/delta.chat now

**Comment by r10s** [comment]
just got another complain:

> grad durch zufall gelernt: `https://delta.chat/enchatmail` leitet weiter zu `https://delta.chat/de/de/de/de/de/de/de/de/de/de/de/de/de/de/de/de/de/de/de/de/enchatmail`
> 
> das sieht für mich nich so ganz richtig aus, soll das so? wer ist dafür verantwortlich?


this is somehow different meanwhile - even if we agree that it is not worse, it is a bad impression and it always costs time to argue that it is not that bad ...

**Comment by missytake** [comment]
There is this test script for the redirects: https://github.com/deltachat/sysadmin/blob/master/page/test-redirects.py

**Comment by r10s** [comment]
closed by #990
