### ISSUE TITLE
URLs with trailing slash are not recognized

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-pages#849]
If you open https://delta.chat/chatmail/ instead of https://delta.chat/chatmail you will experience infinite redirects. There should be a redirect to the same page without slash instead.

See #848

**Comment by r10s** [comment]
let's discuss "redirects" that in a single issue, https://github.com/deltachat/deltachat-pages/issues/848 , i think it is all related, may it be a missing folder or a missing file
