### ISSUE TITLE
FAQ on invite link is missing?

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#862]
seems we don't have much about invite links and only talk about QR code scanning in the FAQ. 
Should change around 1.46 -- the feature is already in 1.44.

**Comment by r10s** [comment]
there was  https://github.com/deltachat/deltachat-pages/pull/831 done recently - to have at least _something_

but yes, that can be improved for sure :)

**Comment by missytake** [comment]
I'd draft something tomorrow if that's enough.
