### ISSUE TITLE
New screenshots for home page (and later stores), write some replication machinery to ease that

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#868]
When releasing 1.46 apps let's do some up-to-date screenshots, first on the home page. 

Let's try to have some interesting conversations and snapshot the accounts, and try to be able to re-generate sscreenshots and the contained dialogues (which should not just be about office lunch, or some party, but about some real drama like the alice/Bob/Mad-hatter dialogues (and there originally also was carol who started an affair with alice or something?) 

maybe we can write a python script that actually creates Alice, Bob, Mad-hatter accounts, sets avatars, sends messages etc. and then provides a number of accounts in a zip file so that one can just import it into Android, ios, desktop and do some snapshots. 
We can evolve the dialogues over time, so something that replicates what we have.  cc @missytake @adbenitez @kermoshina -- could be a fun thing to go for next week at bb :)

**Comment by kermoshina** [comment]
Sure! We can also use our chatbot to generate some fun dialogues. 

![Screenshot_20240513_114604_One UI Home](https://github.com/deltachat/deltachat-pages/assets/16879492/673dda8f-8035-47cf-a1d9-e1e766bb8a56)

![Screenshot_20240513_115117_One UI Home](https://github.com/deltachat/deltachat-pages/assets/16879492/4b747c39-2f96-48b5-b590-38e9a17a41c3)


Also one of the screenshots could accidentally mention webxdc gaming / collab apps.
