### ISSUE TITLE
Built pages for staging.delta.chat have an incorrect modification date

### ISSUE THREAD

**Issue by hagenest** [deltachat/deltachat-pages#898]
As noticed in https://github.com/deltachat/sysadmin/issues/167, pages built by our CI for staging.delta.chat have a modification date of 1970-01-01. To me it looks like this was introduced together when [switching the build to nix](https://github.com/deltachat/deltachat-pages/commit/0d1937ee9e46732a6dee433282ddb554a3ae7552).

**Comment by missytake** [comment]
The problem is even larger I think - pages like delta.chat/es/download are not being updated correctly, they still show 1.44 for the apk download e.g.
