### ISSUE TITLE
Link to paypal donations not working properly

### ISSUE THREAD

**Issue by Foxdelmar** [deltachat/deltachat-pages#9]
Hi,
on your web page the link or the settings to the donations via paypal is not set correctly https://paypal.me/deltachat/10 

I tried to donate some money but it says 

"Dieser Empfänger akzeptiert PayPal-Zahlungen nur über seine Webseite. Um diese Zahlung durchzuführen, besuchen Sie seine Webseite oder schreiben Sie den Empfänger direkt an."

Equals:
The recipient accepts paypal-payments only on his webppage. To make payments, visit his webppage or write the recipient a message

I want to you receive all donations that someone wants to send you without any obstacles. So please check an maybe correct the Paypal-Settings.

Maybe there are a few more people online that would donate or would have donated if they do not get this error message.

Best regards
Fox

**Comment by r10s** [comment]
Thank you for your report, I will check this (seems as if Paypal has changed sth. - IIRC, in the past we received sone donations via the link on our page)

**Comment by Foxdelmar** [comment]
I tried it again. It is still the same:
![grafik](https://user-images.githubusercontent.com/10437953/28242512-82605e7c-69ae-11e7-8dfe-a1df5d4f42c8.png)

**Comment by r10s** [comment]
Yes, sorry, I did not find the time to fix it. I raised it to the top of my todo-list

**Comment by r10s** [comment]
Hm, the Paypal-Backend is really weird and I could not find an option that may fix the problem.

I've asked a question here: https://www.facebook.com/PayPalDeutschland/posts/1428428017192526 as suggested on paypal.com. Text:

> Hallo zusammen, ich habe auf der Seite https://delta.chat/de/ den Link https://www.paypal.me/deltachat/10 gesetzt um Zahlungen zu empfangen.
>
> Ich habe über diesen Link auch Zahlungen empfangen, zuletzt vor ca. 8 Wochen.
>
> Mittlerweile scheint im Paypal-System aber irgendwas geändert worden zu sein, der Link funktioniert nämlich nicht mehr, sondern es wird die Fehlermeldung "Dieser Empfänger akzeptiert PayPal-Zahlungen nur über seine Website. Um diese Zahlung durchzuführen, besuchen Sie seine Website oder schreiben Sie den Empfänger direkt an." angezeigt. (und ich hatte mich schon gewundert, warum keine Zahlungen mehr kommen ...)
>
> Im Websystem habe ich nichts gefunden, was zur Behebung des Fehlers beitragen könnte, eine Google-Suche brachte etliche ähnliche Probleme von anderen Users zutage, aber keine Lösung.
>
> Was kann ich tun damit der paypal.me Link wieder funktioniert?

**Comment by r10s** [comment]
I got an answer from the Paypal support and I could solve the problem. Great! It was the Setting at "Mein Profil -> Kontoeinstellungen -> Verkäufer/Händler -> Zahlungen sperren -> aktualisieren ->Zahlungen über die Option Geld senden" which must be disabled (no checkmark).
