### ISSUE TITLE
Metadata collection

### ISSUE THREAD

**Issue by FedericoCeratto** [deltachat/deltachat-pages#90]
The website reads "Anonymous: Metadata like Who communicates with Whom, When and Where is not collected".
Yet, email providers and 3rd party that can monitor network traffic between them can easily tell who's writing to whom and when.

**Comment by r10s** [comment]
thank you for the hint, maybe this statement can be clarified.

i think the idea of this statement is more the comparison with other centralized messengers as whatsapp, signal, telegram, threema etc. that know everything about who communicates with whom in their silos.

compared with that, delta chat has zero information.

sure, email-providers have the data - but you have a choice, which provider to use. and they only see a relatively small excerpt of the whole image.

**Comment by luisfsr** [comment]
Though it can't see the contents of messages, the email providers can see who communicates with whom, where and when. I also find that this statement should be revised and/or clarified in the website.

**Comment by r10s** [comment]
> the email providers can see who communicates with whom, where and when.

the big difference to "providers" as whats app, signal, threema etc. is the the "email" providers cannot see the whole image; they cannot create a social graph or sth. like that that easy. and Delta Chat also does not collect or send these data somewhere.
also _where_ is relative, compared to apps that share the location. the providers only see the IP.

however, glad to reopen this again - suggestions or pr's welcome :)

**Comment by luisfsr** [comment]
I suggest an asterisk in the mentioned "Why" session of the site linked to a general FAQ entry as follows:

> - **Does Delta Chat collect metadata of its users? Is it possible to determine _Who_ communicates with _Whom_, _When_ and _Where_?**
> Delta Chat does not collect or send these data somewhere. Although, e-mail providers and third party could monitor network traffic and tell _who_'s writing to _whom_ and _when_, compared to other centralized messengers, as whatsapp, signal, threema etc., the the e-mail providers cannot see the whole image; they cannot create a social graph or sth. that easy. Also _where_ is relative, because compared to apps that share the location the e-mail providers only see the IP.
> At last, if you don't trust your current e-mail provider you can choose another one and keep using Delta Chat.

I beg your pardon, but I took the liberty of using your previous posts to write down the current suggestion.

**Comment by r10s** [comment]
i think this issue is gone due to revamped website
