### ISSUE TITLE
Linux desktop anbox instructions no longer work

### ISSUE THREAD

**Issue by dkg** [deltachat/deltachat-pages#92]
`en/help.md` has a section about using deltachat on the linux desktop, that involves using `anbox-installer`.  when i try to follow those instructions, i am told that `anbox-installer` is deprecated.

I haven't yet been able to figure out how to install anbox and get it working in any sensible way, so i don't have a patch to send you for the instructions, but you probably want to know that the instructions are currently not working. :(

**Comment by r10s** [comment]
thank you very much, yes, we should update this. but also the work on a "real" desktop version has started on DeltaX which, of course will then replace the anbox approach :)

**Comment by r10s** [comment]
finally, i moved the instructions to out new forum and added a hint that they need to be updated.

@dkg again, thank you very much.
