### ISSUE TITLE
Redirection problems in lieu of localization 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#957]
[Reported on the fediverse](https://social.anoxinon.de/@Lioh/113157780249093805) 

It is probably related to localization and redirects, a kind of known issue that there is some mess on our nginx deployment. 
Should be reproducable with this link: https://delta.chat/2023-12-13-chatmail  and using a non-english locale. 

![image](https://github.com/user-attachments/assets/8d106b5f-cce9-4f88-92b0-28526c1d793d)

**Comment by r10s** [comment]
the destination is a blogpost, that are just not available in any other language than english. 

therefore, the redirect must not redirect using locales path vars, but always use the english page (maybe the redirect was created  by a copy+paste of a page that has translations)

alternatively or additionally, the original source containing the link could just use the variation using "en" in the path
