### ISSUE TITLE
Add "help" entry about Delta Chat not working with VPN?

### ISSUE THREAD

**Issue by WofWca** [deltachat/deltachat-pages#961]
https://github.com/deltachat/deltachat-pages/blob/master/en/help.md

There have been complains that DC doesn't work via VPN due to the VPN service blocking the required ports. E.g. see "Delta Chat Dev" group:

> I guess this is about the same problem with VPNs that block the common email ports, it will be solved for chatmail with the 443 port support + next-next release, if some russian speaker wants to say something to this person along the lines "it will be fixed for chatmail accounts in future versions" let me the reply here and I will add it

And [this forum post](https://support.delta.chat/t/could-provide-a-set-of-non-standard-ports-on-nine-testrun-org/3157?u=wofwca).
I know this is supposed to be fixed for Chatmail, but still, Delta Chat is supposed to support other email providers.
So, shall we add an entry about this?

**Comment by hpk42** [comment]
On Sat, Sep 28, 2024 at 05:00 -0700, WofWca wrote:
> https://github.com/deltachat/deltachat-pages/blob/master/en/help.md
> 
> There have been complains that DC doesn't work via VPN due to the VPN service blocking the required ports. E.g. see "Delta Chat Dev" group:

do VPNs typically block submission/imap ports? 
How can people run e-mail clients then with such a VPN? 
(IOW, this shouldn't just affect Delta)

**Comment by WofWca** [comment]
> do VPNs typically block submission/imap ports?

I am not sure about commercial VPNs, but if you're running a self-hosted one on a VPS, the VPS might be blocking those ports to prevent spam, AFAIK it's quite common.

> How can people run e-mail clients then with such a VPN?
> (IOW, this shouldn't just affect Delta)

For some people, Delta Chat is just an alternative to WhatsApp. They might not be running an email client, or they might, but something that is simply a web UI for their mail box.
Apart from trying alternative ports and disabling VPN, I don't know what to suggest.

**Comment by hpk42** [comment]
On Sun, Oct 13, 2024 at 12:25 -0700, WofWca wrote:
> > do VPNs typically block submission/imap ports?
> 
> I am not sure about commercial VPNs, but if you're running a self-hosted one on a VPS, the VPS might be blocking those ports to prevent spam, AFAIK it's quite common.

submission/imap ports are *not* the SMTP port (port 25, 
what MTAs aka mail servers use to relay messages). 
I doubt it's common for VPNs to block submission/imap (487, 465)
but fully agree it's likely they block outgoing connections to port 25. 
But the latter does not affect delta chat users connecting to their servers.

**Comment by ralphtheninja** [comment]
I use DeltaChat with a VPN and it works. The only issues I've personally seen are dropping connections, so DeltaChat ends up in a non connected state and have to re-connect with the server. When this happens and you type a message, the message status is "pending" and you see the spinner in the bottom right corner of the message. I've only seen this on mobile though (Android).

When this happens I just have to wait a bit, or kill the app and restart it and then it usually connects immediately.

**Comment by missytake** [comment]
I wouldn't add an FAQ entry about this. At this point it doesn't seem to be asked frequently, the attached forum post was resolved with a software fix for example (ALPN over port 443). If people complain about certain VPN providers blocking some ports we can still create an FAQ about this.

But we can anyway not say more than "if you use a VPN it might not work" and the affected users already see that it does not work with their VPN. We also can not offer a useful solution because it depends so much on their circumstances.

Closing this for now, re-open if you disagree.

**Comment by WofWca** [comment]
> affected users already see that it does not work with their VPN

You might not always connect the dots to realize that it's the VPN that makes Delta Chat stop working. For example, if the VPN is always on.

**Comment by hpk42** [comment]
On Mon, Oct 14, 2024 at 07:20 -0700, WofWca wrote:
> > affected users already see that it does not work with their VPN
> You might not always connect the dots to realize that it's the VPN that makes Delta Chat stop working. For example, if the VPN is always on.

can you point to a real-life reported failure/example failing to use DC with a VPN?

**Comment by WofWca** [comment]
> can you point to a real-life reported failure/example failing to use DC with a VPN?

- It happened to me when I was using a self-hosted VPN.
- See [this comment on the forum](https://support.delta.chat/t/could-provide-a-set-of-non-standard-ports-on-nine-testrun-org/3157/3?u=wofwca)
- There is a review on Google Play Store from 2024-08-21 in Russian asking when it's gonna start working over a VPN.
