### ISSUE TITLE
add GDPR to transifex

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-pages#99]
Hello,
the GDPR page is not  available in Transifex so it can't be translated.

Are you waiting for the https://github.com/deltachat/deltachat-pages/issues/96 ?

**Comment by r10s** [comment]
> Are you waiting for the #96 ?

no, i think it should be translatable, it's just not done by someone :)

however, i would like to have the okay from @jankass before doing so.

**Comment by r10s** [comment]
okay, after a little poll on irc #deltachat, we'll make it translatable but every translated page should refer to the english original.

**Comment by r10s** [comment]
done :)
