### ISSUE TITLE
Improve troubleshooting of second device setup

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#998]
Mention local network permission for iOS and MacOS and where to find them.

I made some screenshots of the settings. We might redo them in English, but German is better than nothing:

|iOS app settings| permission dialog macOS |  MacOS privacy settings |
|---|---|---|
|![image](https://github.com/user-attachments/assets/5749ee23-df2d-45ed-bb35-f9739e739893) |![image](https://github.com/user-attachments/assets/24f7d0df-0a89-4832-a2e8-2d91291c82d1)|![image](https://github.com/user-attachments/assets/22dbcc7e-9714-4683-a8ff-6402027034a6)|

**Comment by r10s** [comment]
thanks for the hints!

iirc, the dialogs pop up automatically, we even trigger them on iOS at least.

but sure, if one has declined the access before or accidentally, it is good to mention that in the faq, +1

we should do that similar as we do for windows

i would not add screenshots, however, that is over the top compared to what we're doing elsewhere, also wrt maintainance and localisation. but we could link to the forum for details, if we think, that is needed
